### ISSUE TITLE
Getting Console Logs @ UI Process

### ISSUE THREAD

**Issue by Vivek-Arumugam** [WebPlatformForEmbedded/WPEWebKit#10]
Hi,

I want to log the console messages in a file and there I stuck because I see no callbacks provided in UI Process to get the console logs. However I saw "willAddMessageToConsole" callback on InjectedBundlePage UI Client (which belongs to WebProcess).

Is there any way to get the console messages at the UI Process itself? If so, what is the way? I was searching for some callbacks to register so far in UI Process.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
