### ISSUE TITLE
Option to disable WebSecurity in webkit

### ISSUE THREAD

**Issue by towolf** [WebPlatformForEmbedded/WPEWebKit#103]
I was trying to patch the webkit sources to make it possible to load into an iframe pages, which formally disallow this for regular browsers. I couldn't make it work.

Would it be possible to add this?

**Comment by blino** [comment]
There are APIs for WebSecurity preferences in Source/WebKit2/UIProcess/API/C/WKPreferencesRefPrivate.h:
void WKPreferencesSetWebSecurityEnabled(WKPreferencesRef preferences, bool enabled);
bool WKPreferencesGetWebSecurityEnabled(WKPreferencesRef preferences);

But they are not exposed in the public headers, this is for internal test usage only.

**Comment by valbok** [comment]
Hi @blino, could you please clarify a bit what do you mean about
"But they are not exposed in the public headers" ?
As I can see this file is located in forwarding headers, and we are able to use it 
    WebKitForWayland$ find ./ -iname "WKPreferencesRefPrivate.h"
    ./Source/WebKit2/UIProcess/API/C/WKPreferencesRefPrivate.h
    ./WebKitBuild/Release/DerivedSources/ForwardingHeaders/WebKit/WKPreferencesRefPrivate.h

if we can use it like:
#include <WebKit/WKPreferencesRefPrivate.h>

Thanks

**Comment by valbok** [comment]
Also could we understand why 
https://github.com/Metrological/WebKitForWayland/blob/master/Source/WebKit2/UIProcess/API/wpe/WPEView.cpp#L59 
web security disabled by default there?
Anyway we need to find a way how to enable it by default.
Thanks

**Comment by blino** [comment]
I mean they are not public since they are not available in /usr/include/wpe-0.1/WPE/WebKit after a standard cmake install.

**Comment by zdobersek** [comment]
I'd be open to make the APIs public and keep the security enabled by default.

**Comment by towolf** [comment]
That would be highly appreciated :+1:

**Comment by towolf** [comment]
@zdobersek have you had time to look into this yet?

**Comment by zdobersek** [comment]
Sorry, this fell off my radar.

Done here: https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/15d284cb219e18eded1d46e2bcf546af6257b671

**Comment by towolf** [comment]
@zdobersek thanks for your fix. And please forgive my ignorance, but where would now be the proper place to put something like webSecurity = false to disable it in WPE?

**Comment by zdobersek** [comment]
@towolf you mean the call to the now-exposed API? Somewhere early in the WK initialization, see e.g. WebBridge:
https://github.com/Metrological/webbridge/blob/master/Plugins/WebKitBrowser/WebKitImplementation.cpp#L860

**Comment by towolf** [comment]
@zdobersek i cannot access that link, seems to be a private repo 😢 .

**Comment by zdobersek** [comment]
@towolf, sorry, was not aware. Same is done in the launcher app:
https://github.com/WebPlatformForEmbedded/WPEWebKitLauncher/blob/master/launcher/main.cpp#L104
