### ISSUE TITLE
Performance: decrease WPELauncher load time: under one second (Pi2, opening a blank page)

### ISSUE THREAD

**Issue by igor-borovkov** [WebPlatformForEmbedded/WPEWebKit#122]
According to Azam current load times (WPELauncher, pi2): 

> Total load time for https://www.google.com/: ~2.2sec
> Total load time for http://test.borovkov.com/empty.html with 2 WPELauncher: ~2sec

REFERENCE: https://www.teamccp.com/jira/browse/WKIT-672

TRACKING TICKET: https://www.teamccp.com/jira/browse/WKIT-698

**Comment by zdobersek** [comment]
For reference, how much time does `wget` require to download those two pages?
