### ISSUE TITLE
[EME] can't play Playready DASH content with latest buildroot-wpe RPi2 image 

### ISSUE THREAD

**Issue by goruklu** [WebPlatformForEmbedded/WPEWebKit#213]
Tried playing PR DASH content using dash.hs v2.3 and bitdash players on the RPi2 but both of them failed. dec12 branches can play the content so it seems to be a regression.

**bitdash link:**
[http://52.8.38.95/bitdash-demo/playready.html](url)
Error log:
`# GST_DEBUG=3 WPELauncher http://52.8.38.95/bitdash-demo/playready.html
[LibinputServer] Initialization of linux input system succeeded.
[WPEInjectedBundle] Initialized.
didClearWindowObjectForFrame
https://bitmovin-a.akamaihd.net/bitmovin-player/beta/7/bitmovinplayer.js:12:347736: CONSOLE LOG %cAdaptive Video Streaming Service by www.bitmovin.com color:blue;font-weight:bold;font-size:14px;
https://bitmovin-a.akamaihd.net/bitmovin-player/beta/7/bitmovinplayer.js:12:360400: CONSOLE LOG Player Version 7.1.0-b5
[WPELauncher] Hello InjectedBundle ...
[WPEInjectedBundle] Hello!
	array item: Test1
	array item: Test2
	array item: Test3
http://52.8.38.95/bitdash-demo/playready.html:128:16: CONSOLE LOG Successfully created bitmovin player instance
0:00:02.927517603  1644   0x3256c0 FIXME                default gstutils.c:3826:gst_pad_create_stream_id_internal:<appsrc1:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:02.932637603  1644   0x325920 FIXME                default gstutils.c:3826:gst_pad_create_stream_id_internal:<appsrc3:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
Closed connection for Provisioning. 3
0:00:04.207678019  1644 0x6f102380 ERROR      webkitmediaplayer MediaPlayerPrivateGStreamerBase.cpp:1554:generateKeyRequest: the key request wasn't properly generated
HTMLMediaElement::webkitGenerateKeyRequest() result 1
0:00:04.378625832  1644   0x325580 FIXME                default gstutils.c:3826:gst_pad_create_stream_id_internal:<appsrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:04.380343592  1644   0x325580 WARN                 qtdemux qtdemux_types.c:223:qtdemux_type_get: unknown QuickTime node type ainf
0:00:04.457243071  1644   0x325980 FIXME                default gstutils.c:3826:gst_pad_create_stream_id_internal:<appsrc2:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:04.458340884  1644   0x325980 WARN                 qtdemux qtdemux_types.c:223:qtdemux_type_get: unknown QuickTime node type ainf
[WPELauncher] 22.80FPS
0:00:05.099118852  1644 0x6f102380 ERROR                default AppendPipeline.cpp:764:didReceiveInitializationSegment: Unsupported stream type or codec
0:00:05.100230207  1644 0x6f102380 WARN                 default AppendPipeline.cpp:1064:disconnectDemuxerSrcPadFromAppsinkFromAnyThread: Not disconnecting demuxer src pad because it wasn't linked
0:00:05.102302759  1644 0x6f102380 WARN                 default AppendPipeline.cpp:1064:disconnectDemuxerSrcPadFromAppsinkFromAnyThread: Not disconnecting demuxer src pad because it wasn't linked
https://bitmovin-a.akamaihd.net/bitmovin-player/beta/7/bitmovinplayer.js:12:405938: CONSOLE WARN MediaSource is not open (readyState=closed)
0:00:05.491921665  1644   0x325580 FIXME                default gstutils.c:3826:gst_pad_create_stream_id_internal:<appsrc5:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:05.494371404  1644   0x325980 FIXME                default gstutils.c:3826:gst_pad_create_stream_id_internal:<appsrc7:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
Closed connection for Provisioning. 3
0:00:06.710759373  1644 0x6f102380 ERROR      webkitmediaplayer MediaPlayerPrivateGStreamerBase.cpp:1554:generateKeyRequest: the key request wasn't properly generated
HTMLMediaElement::webkitGenerateKeyRequest() result 1`

**Dash.js link:**
[http://52.8.38.95/dash.js/samples/playready.html](url)
Error log:
`[LibinputServer] Initialization of linux input system succeeded.
[WPEInjectedBundle] Initialized.
didClearWindowObjectForFrame
didClearWindowObjectForFrame
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [60] EME detected on this user agent! (ProtectionModel_01b) 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [78] Playback Initialized 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [137] [dash.js 2.3.0] MediaPlayer has been initialized 
[WPELauncher] Hello InjectedBundle ...
[WPEInjectedBundle] Hello!
	array item: Test1
	array item: Test2
	array item: Test3
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [410] Parsing complete: ( xml2json: 80.0ms, objectiron: 109ms, total: 0.189s) 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [417] Manifest has been refreshed at Mon Feb 13 2017 20:31:06 GMT+0000 (UTC)[1487017866.06]  
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [440] SegmentTimeline detected using calculated Live Edge Time 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [465] MediaSource attached to element.  Waiting on open... 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [650] MediaSource is open! 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [652] Duration successfully set to: 734.167 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [657] Added 0 inline events 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [662] video codec: video/mp4;codecs="avc1.640028" 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [712] Schedule controller stopping for video 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [756] audio codec: audio/mp4;codecs="mp4a.40.2" 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [771] Schedule controller stopping for audio 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [775] No text data. 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [775] No fragmentedText data. 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [779] No embeddedText data. 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [779] No muxed data. 
0:00:01.543359792  2088  0x19e5a90 FIXME                default gstutils.c:3826:gst_pad_create_stream_id_internal:<appsrc1:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:01.546606198  2088  0x19e5b80 FIXME                default gstutils.c:3826:gst_pad_create_stream_id_internal:<appsrc3:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [827] DRM: KeySystem Access Granted (com.microsoft.playready)!  Selecting key system... 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:26114:28: CONSOLE LOG systemID is 9a04f079-9840-4286-ab92-e65be0885f95
Closed connection for Provisioning. 3
HTMLMediaElement::webkitGenerateKeyRequest() result 0
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2133] Start Event Controller 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2150] Schedule controller starting for video 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2153] Schedule controller starting for audio 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2207] DRM: onKeyMessage 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2211] keymessage is <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><AcquireLicense xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols"><challenge><Challenge xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols/messages"><LA xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols" Id="SignedData" xml:space="preserve"><Version>1</Version><ContentHeader>
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2212] keySystemString com.microsoft.playready 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2212] messageType  license-request 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2213] onKeyMessage: gurdal1 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2213] onKeyMessage: gurdal2 url is http://playready.directtaps.net/pr/svc/rightsmanager.asmx?PlayRight=1&UseSimpleNonPersistentLicense=1 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2214] onKeyMessage: gurdal3 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2220] Native video element event: play 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2261] Init fragment finished loading saving to video's init cache 
0:00:03.004214270  2088  0x19e6af0 FIXME                default gstutils.c:3826:gst_pad_create_stream_id_internal:<appsrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:03.006198072  2088  0x19e6af0 WARN                 qtdemux qtdemux_types.c:223:qtdemux_type_get: unknown QuickTime node type ainf
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2288] Init fragment finished loading saving to audio's init cache 
0:00:03.025406510  2088  0x19e6c90 FIXME                default gstutils.c:3826:gst_pad_create_stream_id_internal:<appsrc2:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:03.025958281  2088  0x19e6c90 WARN                 qtdemux qtdemux_types.c:223:qtdemux_type_get: unknown QuickTime node type ainf
0:00:03.027680572  2088 0x6fd02380 ERROR                default AppendPipeline.cpp:764:didReceiveInitializationSegment: Unsupported stream type or codec
0:00:03.029865728  2088 0x6fd02380 WARN                 default AppendPipeline.cpp:1064:disconnectDemuxerSrcPadFromAppsinkFromAnyThread: Not disconnecting demuxer src pad because it wasn't linked
0:00:03.031712812  2088 0x6fd02380 WARN                 default AppendPipeline.cpp:1064:disconnectDemuxerSrcPadFromAppsinkFromAnyThread: Not disconnecting demuxer src pad because it wasn't linked
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2329] Caught pending play exception - continuing ([object DOMError]) 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2334] Video Element Error: MEDIA_ERR_SRC_NOT_SUPPORTED 
http://52.8.38.95/dash.js/dist/dash.all.debug.js:2917:24: CONSOLE LOG [2334] [object MediaError] `

**Comment by goruklu** [comment]
this error message is seen in the logs:
`ERROR default AppendPipeline.cpp:764:didReceiveInitializationSegment: Unsupported stream type or codec`

**Comment by calvaris** [comment]
The error seems to be in the key init data management from the PlayReady SDK.

**Comment by albertd** [comment]
Resolved
