### ISSUE TITLE
Resizing WPELauncher surface with IVI LayerManagerControl

### ISSUE THREAD

**Issue by walmis** [WebPlatformForEmbedded/WPEWebKit#242]
I'm trying to implement a web view with weston with IVI shell and IVI extensions. By default WPELauncher creates a wayland surface with 800x600 size and everything seems to render normally, but when resizing the surface with LayerManagerControl, the surface resizes to the new size, but the layout is broken and stretched. It seems the new size is not propagated internally to the webkit renderer. 

Steps to reproduce:
Launch weston:
weston --tty=4 --idle-time=0 -c .config/weston-ivi.ini 

weston-ivi.ini
```
[core]
shell=ivi-shell.so
idle-time=0

[ivi-shell]
ivi-module=ivi-controller.so
```
launch WPELauncher:
`WAYLAND_DISPLAY=wayland-0 LD_LIBRARY_PATH=WPE ./WPE/WPELauncher http://www.webkit.org/blog-files/3d-transforms/poster-circle.html`

And resize the surface:
`LayerManagerControl set surface <id> destination region 0 0 1920 1080`

I've poked around in WPE code and noticed there is this code in view-backend-wayland.cpp
which looks like it should notify on resize event, but it does not seem to make a difference.

```
static const struct ivi_surface_listener g_iviSurfaceListener = {
    // configure
    [](void* data, struct ivi_surface*, int32_t width, int32_t height)
    {
        struct wpe_view_backend* backend = static_cast<ViewBackend::ResizingData*>(data)->backend;
        wpe_view_backend_dispatch_set_size(backend, std::max(0, width), std::max(0, height));
        printf("ivi surface configure %d %d\n", width, height);
    },
};
```

Any help would be appreciated

weston version: 1.11.0
I've tried different branches of WPEWebkit, with the same results.
Ubuntu 16.10

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
