### ISSUE TITLE
WebProcess crash in JSC DFG on mips32el platform

### ISSUE THREAD

**Issue by emutavchi** [WebPlatformForEmbedded/WPEWebKit#248]
It asserts on 'http://nxg-frontend.uphe.com/Universal/Minions/MicroHtml/#de31992e-fcde-4714-8afb-825839619b98':

> DFG ASSERTION FAILED: unexpected node in DFG backend

Full log is available here: https://gist.github.com/emutavchi/67ba603bbbb0a319c68dd9521d355070#file-dfg-assert

WPE WebKit at a97f19a9ead6ca8ca91508e7724b747b23375595

**Comment by albertd** [comment]
Could you retry with latest master we added some JIT/DFG patches just after the commit you mentioned.

**Comment by emutavchi** [comment]
Hi Arbert, it crashes on master as well, tried on b5cedc7eb2e1433ecccd91b9acbf964412ce8426. 

Also, we were able to reproduce on armv7l box (rdk-webrtc-dec12 branch). 

And following seems to workaround the issue:

```
diff --git a/Source/JavaScriptCore/dfg/DFGPredictionPropagationPhase.cpp b/Source/JavaScriptCore/dfg/DFGPredictionPropagationPhase.cpp
index 0907b9f..ccfb18c 100644
--- a/Source/JavaScriptCore/dfg/DFGPredictionPropagationPhase.cpp
+++ b/Source/JavaScriptCore/dfg/DFGPredictionPropagationPhase.cpp
@@ -402,7 +402,7 @@ private:
                     break;
                 }
 
-                if (node->child1()->shouldSpeculateNumber()) {
+                if (enableInt52() && node->child1()->shouldSpeculateNumber()) {
                     changed |= mergePrediction(SpecAnyInt);
                     break;
                 }

```

**Comment by guijemont** [comment]
Would you be able to provide a simpler test case (ideally js-only) that reproduces the issue? And what's your idea behind the workaround you provided?

**Comment by guijemont** [comment]
This change upstream: https://github.com/WebKit/webkit/commit/ee0456252070275261d19575711871068c74d608
seems to address the same code in a different way. Might be worth it to see if it applies to our branch and if it helps with your issue?

**Comment by emutavchi** [comment]
Hi Guillaume, I couldn't extract the test case from the website yet. However, I tried the change you mentioned and it does fix the crash. Will you cherry pick the change?

**Comment by guijemont** [comment]
Good that it fixes the crash! I'll run some tests to make sure that the change doesn't break anything if cherry-picked on its own, and then merge it if all is fine.

**Comment by guijemont** [comment]
After running all the tests on i386 with and without the patches, I conclude that it doesn't seem to break anything, so it is now cherry picked on master as of https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/4ba0b05f32d2ee9d8cb3f9795982daca61fd1aff
Please check again that it works for you, and if it does close the bug.

**Comment by guijemont** [comment]
@emutavchi can you confirm this works?

**Comment by emutavchi** [comment]
Hi Guillaume, sorry for late response. I did check in Metro/stable and it works good for me, thanks!
