### ISSUE TITLE
Wpe webkit problem with westeros-wpe-image for rpi

### ISSUE THREAD

**Issue by alcostard** [WebPlatformForEmbedded/WPEWebKit#250]
I'm trying to compile westeros-wpe-image and face some problem. I had a warning message at 40% but it didn't stopped the compile. But when I arrived to 99% then it reappears and stops the compile. I searched but didn't found anything about it. So the problem is the compile get problem with the wpe webkit. I post the log here

> Loading cache...done.
Loaded 2219 entries from dependency cache.
Parsing recipes...done.
Parsing of 1618 .bb files complete (1617 cached, 1 parsed). 2220 targets, 194 skipped, 0 masked, 0 errors.
WARNING: No recipes available for:
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.6.2.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.6.3.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.8.2.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.8.3.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.6.2.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.6.3.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.8.2.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.8.3.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.6.2.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.6.3.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.8.2.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.8.3.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_1.8.2.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0-plugins-ugly_1.8.3.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0_1.6.2.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0_1.6.3.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0_1.8.2.bbappend
  /home/Alexis/meta-wpe/recipes-multimedia/gstreamer/gstreamer1.0_1.8.3.bbappend
  /home/Alexis/meta-wpe/recipes-support/icu/icu_56%.bbappend
  /home/Alexis/meta-wpe/recipes-support/icu/icu_57%.bbappend
NOTE: Resolving any missing task queue dependencies
--
Build Configuration:
BB_VERSION        = "1.33.4"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "universal-4.8"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "raspberrypi2"
DISTRO            = "poky"
DISTRO_VERSION    = "2.2+snapshot-20170419"
TUNE_FEATURES     = "arm armv7ve vfp thumb neon vfpv4 callconvention-hard cortexa7"
TARGET_FPU        = "hard"
meta              
meta-poky         
meta-yocto-bsp    = "master:94467d5087ca3b13e7baac670af107550701b333"
meta-raspberrypi  = "master:4b0bc450e08e6836744c97d21e72600f8320fc05"
meta-96boards     = "master:a38418d43ed4453215d4adc3c4ea440b0c64721b"
meta-wpe          = "master:9be346658ad0ab375dc1a61a53ac3f8ca65a6d83"
meta-oe           
meta-multimedia   = "master:2cdea6c5bb09aa90184c17c9157f4fed0e10b3c2"
--
Initialising tasks...done.
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
NOTE: Running task 2755 of 4703 (/home/Alexis/meta-wpe/recipes-wpe/wpewebkit/wpewebkit_0.1.bb:do_compile)
NOTE: recipe wpewebkit-0.1+gitAUTOINC+4983973988-r0: task do_compile: Started
Log data follows:
| DEBUG: Executing shell function do_compile
| [1/1014] Generate bindings (WebCoreBindings)
| [2/150] cd /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/build/Source/WebKit2 && /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/recipe-sysroot-native/usr/bin/perl-native/perl /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Scripts/generate-forwarding-headers.pl --include-path /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2 --output /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/build/DerivedSources/ForwardingHeaders --platform wpe --platform soup
| [3/150] Building CXX object Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/WebKit2InitializeWPE.cpp.o
| [4/150] Building CXX object Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebTouchEventWPE.cpp.o
| FAILED: Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebTouchEventWPE.cpp.o
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++     @Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebTouchEventWPE.cpp.o.rsp -MD -MT Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebTouchEventWPE.cpp.o -MF Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebTouchEventWPE.cpp.o.d -o Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebTouchEventWPE.cpp.o -c /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/NativeWebTouchEventWPE.cpp
| In file included from /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/NativeWebTouchEventWPE.cpp:29:0:
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/WebEventFactory.h:43:12: error: 'WebTouchEvent' does not name a type
|      static WebTouchEvent createWebTouchEvent(struct wpe_input_touch_event*);
|             ^~~~~~~~~~~~~
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/NativeWebTouchEventWPE.cpp:33:1: error: 'NativeWebTouchEvent' does not name a type
|  NativeWebTouchEvent::NativeWebTouchEvent(struct wpe_input_touch_event* event)
|  ^~~~~~~~~~~~~~~~~~~
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/NativeWebTouchEventWPE.cpp:36:1: error: expected unqualified-id before '{' token
|  {
|  ^
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/NativeWebTouchEventWPE.cpp:46:1: error: expected '}' at end of input
|  } // namespace WebKit
|  ^
| [5/150] Building CXX object Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebMouseEventWPE.cpp.o
| FAILED: Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebMouseEventWPE.cpp.o
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++     @Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebMouseEventWPE.cpp.o.rsp -MD -MT Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebMouseEventWPE.cpp.o -MF Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebMouseEventWPE.cpp.o.d -o Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebMouseEventWPE.cpp.o -c /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/NativeWebMouseEventWPE.cpp
| In file included from /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/NativeWebMouseEventWPE.cpp:29:0:
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/WebEventFactory.h:43:12: error: 'WebTouchEvent' does not name a type
|      static WebTouchEvent createWebTouchEvent(struct wpe_input_touch_event*);
|             ^~~~~~~~~~~~~
| [6/150] Building CXX object Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebWheelEventWPE.cpp.o
| FAILED: Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebWheelEventWPE.cpp.o
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++     @Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebWheelEventWPE.cpp.o.rsp -MD -MT Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebWheelEventWPE.cpp.o -MF Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebWheelEventWPE.cpp.o.d -o Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebWheelEventWPE.cpp.o -c /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/NativeWebWheelEventWPE.cpp
| In file included from /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/NativeWebWheelEventWPE.cpp:29:0:
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/WebEventFactory.h:43:12: error: 'WebTouchEvent' does not name a type
|      static WebTouchEvent createWebTouchEvent(struct wpe_input_touch_event*);
|             ^~~~~~~~~~~~~
| [7/150] Building CXX object Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebKeyboardEventWPE.cpp.o
| FAILED: Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebKeyboardEventWPE.cpp.o
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++     @Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebKeyboardEventWPE.cpp.o.rsp -MD -MT Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebKeyboardEventWPE.cpp.o -MF Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebKeyboardEventWPE.cpp.o.d -o Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/NativeWebKeyboardEventWPE.cpp.o -c /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/NativeWebKeyboardEventWPE.cpp
| In file included from /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/NativeWebKeyboardEventWPE.cpp:29:0:
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/WebEventFactory.h:43:12: error: 'WebTouchEvent' does not name a type
|      static WebTouchEvent createWebTouchEvent(struct wpe_input_touch_event*);
|             ^~~~~~~~~~~~~
| [8/150] Building CXX object Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/ProcessExecutablePathWPE.cpp.o
| [9/150] Building CXX object Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/WebEventFactory.cpp.o
| FAILED: Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/WebEventFactory.cpp.o
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++     @Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/WebEventFactory.cpp.o.rsp -MD -MT Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/WebEventFactory.cpp.o -MF Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/WebEventFactory.cpp.o.d -o Source/WebKit2/CMakeFiles/WebKit2.dir/Shared/wpe/WebEventFactory.cpp.o -c /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/WebEventFactory.cpp
| In file included from /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/WebEventFactory.cpp:27:0:
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/WebEventFactory.h:43:12: error: 'WebTouchEvent' does not name a type
|      static WebTouchEvent createWebTouchEvent(struct wpe_input_touch_event*);
|             ^~~~~~~~~~~~~
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/WebEventFactory.cpp:154:16: error: 'WebPlatformTouchPoint' in namespace 'WebKit' does not name a type
|  static WebKit::WebPlatformTouchPoint::TouchPointState stateForTouchPoint(int mainEventId, const struct wpe_input_touch_event_raw* point)
|                 ^~~~~~~~~~~~~~~~~~~~~
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/WebEventFactory.cpp:174:1: error: 'WebTouchEvent' does not name a type
|  WebTouchEvent WebEventFactory::createWebTouchEvent(struct wpe_input_touch_event* event)
|  ^~~~~~~~~~~~~
| [10/150] Building CXX object Source/WebKit2/CMakeFiles/WebKit2.dir/UIProcess/API/C/cairo/WKIconDatabaseCairo.cpp.o
| [11/150] Building CXX object Source/WebKit2/CMakeFiles/WebKit2.dir/WebProcess/WebPage/WebPage.cpp.o
| FAILED: Source/WebKit2/CMakeFiles/WebKit2.dir/WebProcess/WebPage/WebPage.cpp.o
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++     @Source/WebKit2/CMakeFiles/WebKit2.dir/WebProcess/WebPage/WebPage.cpp.o.rsp -MD -MT Source/WebKit2/CMakeFiles/WebKit2.dir/WebProcess/WebPage/WebPage.cpp.o -MF Source/WebKit2/CMakeFiles/WebKit2.dir/WebProcess/WebPage/WebPage.cpp.o.d -o Source/WebKit2/CMakeFiles/WebKit2.dir/WebProcess/WebPage/WebPage.cpp.o -c /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/WebProcess/WebPage/WebPage.cpp
| In file included from /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/WebProcess/WebPage/WebPage.cpp:77:0:
| /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/git/Source/WebKit2/Shared/wpe/WebEventFactory.h:43:12: error: 'WebTouchEvent' does not name a type
|      static WebTouchEvent createWebTouchEvent(struct wpe_input_touch_event*);
|             ^~~~~~~~~~~~~
| ninja: build stopped: subcommand failed.
| WARNING: /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/temp/run.do_compile.1403:1 exit 1 from '/home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/recipe-sysroot-native/usr/bin/ninja -j 8 libWPEWebKit.so libWPEWebInspectorResources.so WPEWebProcess WPENetworkProcess WPEDatabaseProcess'
| ERROR: Function failed: do_compile (log file is located at /home/Alexis/rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/wpewebkit/0.1+gitAUTOINC+4983973988-r0/temp/log.do_compile.1403)
NOTE: recipe wpewebkit-0.1+gitAUTOINC+4983973988-r0: task do_compile: Failed
NOTE: Tasks Summary: Attempted 4665 tasks of which 4664 didn't need to be rerun and 1 failed.
--
Summary: 1 task failed:
  /home/Alexis/meta-wpe/recipes-wpe/wpewebkit/wpewebkit_0.1.bb:do_compile
Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.`

I used this tutorial for the compile "https://github.com/Comcast/rdk-on-raspberrypi"

If you have any idea to help me, Ill take it !

**Comment by SteffenDE** [comment]
I know this is an old issue, but you could try using https://github.com/WebPlatformForEmbedded/meta-wpe. This worked for me for the RPi 3.

If you got it working it would be nice if you could close the issue.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
