### ISSUE TITLE
On slower CPUs, Youtube TV navigation is behaving incorrectly

### ISSUE THREAD

**Issue by vertexodessa** [WebPlatformForEmbedded/WPEWebKit#265]
To emulate slow CPU on raspberry PI2 with buildroot, 
```
while :; do :; done &
while :; do :; done &
while :; do :; done &
while :; do :; done &
nice -n1 wpe https://www.youtube.com/tv

```

Then select a video and navigate to the right quickly several times.
You will observe that playback window will be shifted to the left.
This happens because an offscreen element (located to the right of the screen) gets focused and view area is scrolled.

**Comment by wouterlucas** [comment]
Hi @vertexodessa we can only reproduce this briefly: 
https://www.dropbox.com/s/8pnrpwpdht5cy6u/YouTube%20slow%20cpu%20navigation.mov?dl=0

Is that the same as what you are experiencing? In the movie I can see it shifts left for about 1 second, then it jumps back to normal.

**Comment by vertexodessa** [comment]
@wouterlucas  hi Wouter, sorry for the delayed responce,
yes, it looks same, also intermittently this artifact also can stay on the screen.
I think the reason of this artifact, is that Youtube tries to focus an offscreen element.
This is usually preceeded by a call to scrollToOffsetWithoutAnimation (ScrollAnimator.cpp)

**Comment by ravurus** [comment]
@wouterlucas any update on this ticket?

**Comment by magomez** [comment]
I'm looking into it. I had to use a rpi1 cause I wasn't able to reproduce it on a rpi2, but I can see it now.

**Comment by magomez** [comment]
What happens is that with each right arrow click, the next element in the list gets the keyboard focus, and then the animation to move the list to the left starts. But if right clicks come too fast, the focus will advance faster than the animation, and at a point the focus will go to an element that is out of the screen and then webkit will scroll to make it visible.

It's not a bug really, just a lack of performance. Actually to me it seems more a problem of youtube tv, which should be discarding key presses that come faster than the animation if too many are received. I guess they didn't think of it as this is only a problem in low end hardware.

Anyway, as this is not an error in webkit operation, the only solution I can think of is delaying keyboard events to they don't come too fast. I'm thinking of an env variable that can be assigned a time to delay the events, and can be tweaked for each platform.

**Comment by magomez** [comment]
I've just added commit 254e68d1dcd1a9daa9861e6f12b1a7de6fe541bd to WPE master to improve this.
I had a better idea than delaying the key events, and it's disabling the behaviour of scrolling to the focused element. I've added a check for the environment variable WPE_DISABLE_SCROLL_TO_FOCUSED to disable this behaviour. Using this variable makes the issue non reproducible, as even if the focused element is out of the screen, no scroll will happen.

I strongly recommend to use this variable only for very concrete cases like the youtube tv page, where the interaction with the used is completely controlled by js and the scroll-to-focus-item behaviour is not needed (at least I didn't find it needed). In pages that rely on this behaviour, like forms that can be navigated using the focus chain (by pressing tab to go to the next input element for example), the scroll won't happen.

Lastly, I added this as an env variable but it can be turned into a setting if you think it's a better option.

@vertexodessa can you give this a try and ensure that it's a valid fix for your case?

**Comment by vertexodessa** [comment]
> I strongly recommend to use this variable only for very concrete cases like the youtube tv page

as we re-use web pages (web processes), we need to modify the behavior without restarting Webkit..
I don't think it's possible with environment variable approach

**Comment by magomez** [comment]
Ok, I'll add it as a setting then.

**Comment by magomez** [comment]
@vertexodessa, I've just pushed commit ae1b1e5d1e2a1e35a880a096823659ab4542a90a that adds the setting. That should be enough to fix you problem.

**Comment by vertexodessa** [comment]
@magomez @wouterlucas Thanks Guys, sorry I'm on vacation this week but we'll integrated the suggested solution soon
Thanks for the implementation!
