### ISSUE TITLE
Is there an API to set custom headers for a request?

### ISSUE THREAD

**Issue by vertexodessa** [WebPlatformForEmbedded/WPEWebKit#274]
We need to set custom headers for some URLs, is there an API for that?
Thanks!

**Comment by wouterlucas** [comment]
Do you mean on XHR requests, like https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader ?

**Comment by vertexodessa** [comment]
hi Wouter, I mean WK API to set custom headers for WKPage/WKFrame

**Comment by carlosgcampos** [comment]
WKBundlePageResourceLoadClient::willSendRequestForFrame

**Comment by valbok** [comment]
@carlosgcampos Hi, to use it from WKBundlePageResourceLoadClient::willSendRequestForFrame
it would require to extend WKURLRequest and API::URLRequest APIs to pass headers to WebCore::ResourceRequest m_request

Maybe it could be better than extending InjectedBundlePageLoaderClient

**Comment by carlosgcampos** [comment]
Ah, I didn't know WKURLRequest doesn't allow to modify headers. I think it would be better to add such API instead of adding another callback to the client.

**Comment by valbok** [comment]
As suggested Carlos, introduced WKURLRequestSetHTTPHeaderField
to set custom header fields.
And now it could be used from WKBundlePageResourceLoadClient::willSendRequestForFrame

**Comment by vertexodessa** [comment]
fixed in https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/291
