### ISSUE TITLE
IR KEY_MENU return keycode

### ISSUE THREAD

**Issue by karora123** [WebPlatformForEmbedded/WPEWebKit#280]
Just like other IR Keys (XFinity IR Remote) such at KEY_RIGHT, KEY_LEFT the Webkit having mapping keycode is 39 and 37 respectively. For KEY_MENU it should be 18 whereas it is 0. Does it supported KEY_MENU?

**Comment by albertd** [comment]
Javascript doesn't have a mapping for the menu key, maybe you could map it to ESC ?

**Comment by karora123** [comment]
So does that mean a javascript file is responsible to handle keyboard events and returning the mapped keycode for linux platform? Which JavaScript file is this? In earlier release its been take care KeyMappingLinuxInput.cpp for linux platform.

**Comment by karora123** [comment]
I have checked my JS file which is getting zero as value for KEY_MENU while for others values seems correct. From code go through it seems file from thirdparty directory "input-libxkbcommon.cpp" should entertaining the Key code and push mapped value to Java Script. But this file not getting compiled which means some other native default key handling exists. Could you please point me to that file.

**Comment by albertd** [comment]
Please have a look at this repo: https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/blob/master/src/input/LinuxInput/input-linuxinput.cpp

**Comment by karora123** [comment]
Thanks albertd....I explored the same yesterday....In my case its libxkbcommon key mapping library is responsible for keysym mappings.
Thanks...it serve the purpose.
