### ISSUE TITLE
memory leak in WPEWebProcess

### ISSUE THREAD

**Issue by karora123** [WebPlatformForEmbedded/WPEWebKit#283]
Hi,

WPEWebkit source info
SRCREV ?= "49839739880a661635ed65cecc2a0591cdf6fa87"
BASE_URI ?= "git://github.com/WebPlatformForEmbedded/WPEWebKit.git;protocol=http;branch=master"

Observed that WPEWebProcess keep increasing the memory utilization and within 30 to 45 min that reaches to  90% approximate as shared below Video got hanged. No crash observed.

 PID USER      PR  NI    VIRT    RES    SHR     S  %CPU   %MEM     TIME+ COMMAND                                                                                                             
 **919  root         20   0     836884 474144  26940 S      29.1    87.6        15:18.05 WPEWebProcess**

**Comment by albertd** [comment]
Which page are you using to produce this?

**Comment by karora123** [comment]
Youtube Video in sequence using youtube tv app.

**Comment by albertd** [comment]
Which hardware platform? And which export flags do you define before starting WPEWebKit?

**Comment by karora123** [comment]
Integrated for Raspberry Pi platform and exported XDG_RUNTIME_DIR as /run/user/0/ and WAYLAND_DISPLAY as WPE.

**Comment by albertd** [comment]
Try setting the following exports:

`export WPE_RAM_SIZE="128m"`
`export WPE_POLL_MAX_MEMORY="databaseprocess:50m,networkprocess:100m,webprocess:300m,rpcprocess:50m"`
`export MSE_MAX_BUFFER_SIZE="audio:2m,video:15m,text:1m"`

And make sure your config.txt has the correct memory split:

`gpu_mem_256=128`
`gpu_mem_512=196`
`gpu_mem_1024=256`

Furthermore are you using a Pi3?

**Comment by karora123** [comment]
Yes, Using Pi3..!!

**Comment by karora123** [comment]
Using RPi3, memory split between cpu and gpu is 752 and 256 MB respectively.
I have configured the environment variable but problem still persists.

**Comment by arunakiran-chennubhatla** [comment]
I tried running video on YouTube App for couple of hours but issue is not reproducible on RPi2.

**Comment by karora123** [comment]
Hi,
Thanks for the update.....Well...could you please share me the wpewebkit source information like branch & tag. Also please update if you have applied any environment settings before running video.

**Comment by arunakiran-chennubhatla** [comment]
I tried with following 
Branch    : master
WPEWebKit : #4ee5ebb149d1be94f0fea4fca64c4c42ea8e6bb7
Buildroot : #16b9af8856fa2687fc475258191425193fb05ce9
In order to avoid "QUOTA_EXCEEDED_ERR" error, I modified config.json and changed the value of msebuffers from "audio:2m,video:15m,text:1m" to  "audio:4m,video:30m,text:1m".

**Comment by karora123** [comment]
Ok...thanks for your inputs...I shall tried executive this way and share the updates. Meanwhile, did you see any slow responsiveness while navigating through youtube.com/tv App home page?

**Comment by gt945** [comment]
this is part of log
```
SourceBuffer::removeCodedFrames(0xe4ec6240) - removing sample({PTS({65880000/1000000 = 65.880000}), DTS({65880000/1000000 = 65.880000}), duration({40000/1000000 = 0.040000})})
SourceBuffer::removeCodedFrames(0xe4ec6240) - removing sample({PTS({65920000/1000000 = 65.920000}), DTS({65920000/1000000 = 65.920000}), duration({40000/1000000 = 0.040000})})
SourceBuffer::removeCodedFrames(0xe4ec6240) - removing sample({PTS({65960000/1000000 = 65.960000}), DTS({65960000/1000000 = 65.960000}), duration({40000/1000000 = 0.040000})})
SourceBuffer::removeCodedFrames(0xe4ec6240) removed 902014 bytes, start(62.080000), end(66.040001)
SourceBuffer::removeCodedFrames(0xe4ec6240) - start({66080000/1000000 = 66.080000}), end({70040000/1000000 = 70.040000})
SourceBuffer::removeCodedFrames(0xe4ec6240) - removing sample({PTS({66200000/1000000 = 66.200000}), DTS({66040000/1000000 = 66.040000}), duration({40000/1000000 = 0.040000})})
SourceBuffer::removeCodedFrames(0xe4ec6240) - removing sample({PTS({66080000/1000000 = 66.080000}), DTS({66080000/1000000 = 66.080000}), duration({40000/1000000 = 0.040000})})
SourceBuffer::removeCodedFrames(0xe4ec6240) - removing sample({PTS({66120000/1000000 = 66.120000}), DTS({66120000/1000000 = 66.120000}), duration({40000/1000000 = 0.040000})})
SourceBuffer::removeCodedFrames(0xe4ec6240) - removing sample({PTS({66160000/1000000 = 66.160000}), DTS({66160000/1000000 = 66.160000}), duration({40000/1000000 = 0.040000})})
```
the sample with pts 66.040000 not be removed.

This bug is relate to below line:
https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/1000e9fab366d3bd0d2d623b4cc478827d48827f/Source/WebCore/Modules/mediasource/SourceBuffer.cpp#L710

**Comment by davedx** [comment]
Any update on this issue?

**Comment by wouterlucas** [comment]
Hi @davedx , this is a pretty old PR and would apply to our current stable branch on WPE WebKit. The stable branch is "stable" and will play video for a long duration without issues. So does the yt2016-emev1 branch which is a newer WebCore with older eme/mse support.  Current WPE WebKit master is being stablized as the latest MSE and EMEv3 specs are completed, @eocanha just reinstated the memory managers and our current tests show the video playback is stable. Though we're continue to run tests and evaluate this. 

Let us know if you are running into concrete issues while testing them and please refer to a recent revision of where you've encountered it.
