### ISSUE TITLE
[MSE][GStreamer][seek] After seek, playback resumed and immediately stuck

### ISSUE THREAD

**Issue by vertexodessa** [WebPlatformForEmbedded/WPEWebKit#284]
Attaching the log:

[seek_to_buffered.log.gz](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1043927/seek_to_buffered.log.gz)

Reproduced on Raspberry PI2

**Comment by vertexodessa** [comment]
Attaching another reproduction case. There was,
`SourceBuffer::sourceBufferPrivateAppendComplete(0x5c5d2d80) - buffered = [{370009977/1000000, 370.009977}..{400010157/1000000, 400.010157}]
`
then, 
`HTMLMediaElement::seek(0x6ead9080) - {4645234317214089216/10000000, 371.000000}
`however, 
`MediaPlayerPrivateGStreamerMSE.cpp:674:isTimeBuffered: Time 371.000000 buffered? No`

[another_seek_hang.log.gz](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1043953/another_seek_hang.log.gz)

**Comment by vertexodessa** [comment]
After some more analysis, I can see the cases are different. 
In the former case, the playback was resumed for a second or so, then there was a flush and it stuck.
In the latter case, the playback did not resume after the seek.
Just for clarity, I am going to create a separate issues for both.

**Comment by vertexodessa** [comment]
Created https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/285 for the latter case, going to delete unrelated comments from here to avoid confusion.

**Comment by eocanha** [comment]
I couldn't reliably reproduce this issue on RPI2. I'm currently investigating other seek issues as I find (reproduce) them.

**Comment by wouterlucas** [comment]
Fixed by commits related to #271
