### ISSUE TITLE
[MSE][GStreamer][seek] After seek to buffered range, playback did not resume

### ISSUE THREAD

**Issue by vertexodessa** [WebPlatformForEmbedded/WPEWebKit#285]
There was,
`SourceBuffer::sourceBufferPrivateAppendComplete(0x5c5d2d80) - buffered = [{370009977/1000000, 370.009977}..{400010157/1000000, 400.010157}]
`
then, 
`HTMLMediaElement::seek(0x6ead9080) - {4645234317214089216/10000000, 371.000000}
`
however, 
`MediaPlayerPrivateGStreamerMSE.cpp:674:isTimeBuffered: Time 371.000000 buffered? No`

[log.gz](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1043953/another_seek_hang.log.gz)

Reproduced on raspberry PI2

**Comment by wouterlucas** [comment]
Fixed by commits related to #271
