### ISSUE TITLE
[MSE][GStreamer][seek] After seek, data was not appended to PlaybackPipeline (it was not ready)

### ISSUE THREAD

**Issue by vertexodessa** [WebPlatformForEmbedded/WPEWebKit#288]
[PLAYBACK_PIPELINE_FULL__.txt.gz](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1044007/PLAYBACK_PIPELINE_FULL__.txt.gz)

**Comment by eocanha** [comment]
Commits https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/7fb21a9b680482630b1cb8ee881666b34fb8d334 and https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/3cd4d31a10ecf2664388d622190652f1541613e4 may have solved this issue. Please, retest.

**Comment by wouterlucas** [comment]
Fixed by commits related to #271
