### ISSUE TITLE
Unable to build WPE in debug mode

### ISSUE THREAD

**Issue by vertexodessa** [WebPlatformForEmbedded/WPEWebKit#292]
Getting the following link errors:
```
lib/libWPEWebKit.so.0.0.20161117: undefined reference to `JSC::HeapCell::markedBlock() const'
lib/libWPEWebKit.so.0.0.20161117: undefined reference to `JSC::JSCell::structure() const'
lib/libWPEWebKit.so.0.0.20161117: undefined reference to `JSC::JSCell::inherits(JSC::ClassInfo const*) const'
lib/libWPEWebKit.so.0.0.20161117: undefined reference to `JSC::Heap::heap(JSC::HeapCell const*)'
lib/libWPEWebKit.so.0.0.20161117: undefined reference to `JSC::HeapCell::isLargeAllocation() const'
lib/libWPEWebKit.so.0.0.20161117: undefined reference to `JSC::HeapCell::largeAllocation() const'

```

**Comment by vertexodessa** [comment]
I was building WPE in Debug but with -O2 flag, that might be a possible reason of optimizing out inlines

**Comment by wouterlucas** [comment]
Please make sure the debug flags are correctly set, tested this and it needed small corrections on our side. It should work with -DNDEBUG and/or 'CMAKE_C_FLAGS_DEBUG="-O0 -g -Wno-cast-align' & 'CMAKE_CXX_FLAGS_DEBUG="-O0 -g -Wno-cast-align' flags just fine.

For an example on how we set the flags on our end please see: https://github.com/WebPlatformForEmbedded/buildroot/blob/master/package/wpe/wpewebkit/wpewebkit.mk#L180-L200
