### ISSUE TITLE
Delayed key navigation impact

### ISSUE THREAD

**Issue by karora123** [WebPlatformForEmbedded/WPEWebKit#293]
Hi,

Key navigation impact on display page (third party UI) observed with delay. Also sometimes page appear with navigation impact not properly painted (shades with overlapping appears). 

Is this known issue?

WPEWebkit source info
SRCREV ?= "49839739880a661635ed65cecc2a0591cdf6fa87"
BASE_URI ?= "git://github.com/WebPlatformForEmbedded/WPEWebKit.git;protocol=http;branch=master"

**Comment by wouterlucas** [comment]
Hi Karora123, not that I'm aware of. Can you provide more context in what the UI is doing? What is the device you are running this on (rpi?). If you have a URL that we could look at that would even be better, as reproducing rendering errors is a huge help. 

Else a video and/or screenshots help tremendously as well.

**Comment by karora123** [comment]
Hi Wouterlucas, Sorry for delay in response. Tried youtube tv app and had following observations
1. Focus not shifting properly on key navigation request as in video shared link.
2. While playing if used MENU button to go back to home page, it displays console initially rather youtube home page. The home page appeared only after pressing any remote key (navigation, menu or any mapped key).
3. observation captured on Raspberry Pi 3 device.
link to video as below.
https://www.youtube.com/watch?v=IBNqhzgPT5o&feature=youtu.be

**Comment by wouterlucas** [comment]
That's an odd aspect ratio for a rpi3 :-) what kind of image are you running on the rpi3? Is it built through https://github.com/WebPlatformForEmbedded/buildroot/ or https://github.com/WebPlatformForEmbedded/meta-wpe ?

I just checked the latest on BR and I do not see the same, no delay and focus is shifted just fine. If you're running a custom rpi image and prefer not to use buildroot or openembedded, its probably best to start aligning packages. I'd start with rpi userland and rpi firmware and see from there.

**Comment by karora123** [comment]
Hi,
I am using meta layer (https://github.com/Metrological/meta-metrological Revision c8a66ff9e2d6c480d0f2f17408cea1d7cadc4885) to build wpewebkit. The meta layer having webkit reference as (https://github.com/WebPlatformForEmbedded/WPEWebKit with revision 49839739880a661635ed65cecc2a0591cdf6fa87)

**Comment by karora123** [comment]
Hi,
Have tried building using (https://github.com/WebPlatformForEmbedded/meta-wpe). Issue seems remain same. :(...will explore further..meanwhile please update if you find anything in this way.

**Comment by wouterlucas** [comment]
That should be fine, are you using some sort of capture device instead of a TV? There may be an issue with Westeros not being able to detect the resolution/aspect ratio, hence messing up the output. Judging by the video it seems to run in an awkward resolution. I believe there was a way to force it, but have to dive into where to set that.

**Comment by karora123** [comment]
Using HDMI port standard TV as output device. May be westeros might cause for this. 
You mean some change required at webkit site to instruct westeros for particular resolution or westeros itself select resolution for display application?

**Comment by karora123** [comment]
Any update so far?? has anyone faced such issue?

**Comment by karora123** [comment]
Hi wouterlucas,

Can you please confirm the reference point of source code & build instruction for which WPEBrowser with westeros works smooth for Raspberry Pi platform.

regards,
Kulbhushan

**Comment by wouterlucas** [comment]
Hi Kaulbhushan,

Certainly, instructions are found on their respective build environments readme's:
https://github.com/WebPlatformForEmbedded/meta-wpe/blob/master/README.md
https://github.com/WebPlatformForEmbedded/buildroot/blob/master/README.md

And support documentation for RPI can be found under RDKV:
https://github.com/Comcast/rdk-on-raspberrypi

Latest WPEWebkit hash that we've tested is: bb9d8436c4051fcf7e957c6fec1e3d2a74d384fb 
Currently though we're moving to the latest Yocto version (rocko), that is being retested. The Pyro branch is a bit more stable if you'd like to avoid rocko related changes.

Hope that helps!
Wouter

**Comment by karora123** [comment]
Hi Wouter,

Thanks for the quick response buddy !! I shall certainly execute as per instruction. If by chance, that did not work, then I believe that must be due to aspect ratio or resolution stuff !! Anyways thanks again shall keep you posted.

Best Regards,
KUL

**Comment by karora123** [comment]
Hi Wouter,

I have been through the shared link and created raspberry based wpe minimal image.  I need to fix the cairo build issue while creating image. 
With this image,  did not see any delay while youtube page navigation. seems working fine.  Hence, closing the ticket. Thanks for support!!

regards,
Kulbhushan

**Comment by wouterlucas** [comment]
You're welcome!
