### ISSUE TITLE
Integrate NodeJS to WPE

### ISSUE THREAD

**Issue by abihf** [WebPlatformForEmbedded/WPEWebKit#3]
Is there any plan to integrate node js to WPE, like http://nwjs.io/ do? So we can access IO and other resources from DOM.

**Comment by albertd** [comment]
Not yet, but would be very interesting, do you think you can contribute as well?

**Comment by abiehaf** [comment]
I'm still reading the codes. Please, tell me if you start implementing it.


Regards,

Abi Hafshin Alfarouq
http://hafs.in/

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
