### ISSUE TITLE
Web inspector Elements tab is not working

### ISSUE THREAD

**Issue by vertexodessa** [WebPlatformForEmbedded/WPEWebKit#309]
When I try to click on any of the elements, I get the following error:
http://imgur.com/2rlttYR
it can be worked around by applying following hack:
https://gist.github.com/vertexodessa/f302e84e69ff703288f5ca61ac277226

Would be much better to have a fix though

**Comment by wouterlucas** [comment]
Fixed by 4e778b56897b69352ef81128d424c5ccd62b712f
