### ISSUE TITLE
Combo of translateZ and "backface-visibility: hidden" breaks "border-radius"

### ISSUE THREAD

**Issue by igor-borovkov** [WebPlatformForEmbedded/WPEWebKit#311]
Usage of translateZ and "backface-visibility: hidden" breaks "border-radius" (corners are not rounded)

```html
<!--BUG: translateZ(0) + backface-visibility breaks border-radius -->

<style>
body {
	background-color: #E3E5EB; 
}
</style>

<div style=" -webkit-transform: translateZ(0);"></div>		

<img style="border-radius: 12px; -webkit-backface-visibility: hidden;" src="your own image file here">	
```

**Comment by magomez** [comment]
I've been able to reproduce this, both with downstream and upstream code. It's related somehow with the usage of accelerated compositing and, curiously, doesn't happen if in the test code the div with translateZ is not empty. I tried putting another there and then the border-radius works properly. I'll keep investigating.

**Comment by igor-borovkov** [comment]
the actual scenario was reproduced on a somewhat complicated website, I tried to minimize the html / css as much as possible but to keep it still reproducible. There are many tiny modifications possible that stop this issue to be triggered, like if putting another div inside the current one, but would be triggered again if the internal div (height) is taller then the current one (after setting "height" to it), and would be triggered if height(s) of both DIVs were set to 0 etc.

**Comment by magomez** [comment]
I think I isolated the problem to a single situation: the rendering is wrong if the image is pushed to its own RenderLayer and the border is not visible. I'm pretty sure all your scenarios will work if you add "border: 1px solid;" to the image style.

The fix is not trivial, but I'm working on it.

**Comment by magomez** [comment]
I'm managing this as an upstream bug in https://bugs.webkit.org/show_bug.cgi?id=174157. As soon as the patch gets commited upstream I'll port it to WPE.

**Comment by magomez** [comment]
I've just pushed 9a02007ed0010dc8adb5526d20aff7213f8324cb that should fix this issue. @igor-borovkov, can you test whether this fixes all your issues, please? Also, please test #310 as well, as I'm pretty sure it's the same issue and it will be fixed with this patch too.

**Comment by igor-borovkov** [comment]
I verified this one. Border radius is fine with this temporary fix now. But #310 is more than just border-radius, there are at least three rendering issues happening in our released webapp when video tag is present on a page. I thought they would be all related. I guess I'd have to try to come up with sample html / css repro code for other issues.

**Comment by magomez** [comment]
Ok, let's close this then.
