### ISSUE TITLE
WPE and openrtc on RPI

### ISSUE THREAD

**Issue by nidhichadha1** [WebPlatformForEmbedded/WPEWebKit#312]
We have been working  to use WPE browser on RPI  to use open RTC and  create connection with simple webrtc streaming server ( already tested with IE and chrome om Windows ) for remote camera video rendering on WPE browser . 

Branch used : master 
Peerconnection works OK with success ; after enabling the flag WEB_RTC  but WPE  or webcore module in WPE is never able to send the local descriptors of the browser while creating the SDP Offer . 

Has anyone faced this issue on master dev branch ?  
Should  openwebrtc-rpi branch handle such scenarios or master branch supports this with known patch  ? 

Thanks
Nidhi

**Comment by albertd** [comment]
Please have a look at this pull request: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/538
