### ISSUE TITLE
WKCookieManager changes

### ISSUE THREAD

**Issue by estobbart** [WebPlatformForEmbedded/WPEWebKit#319]
What's the purpose of exposing getters/setters for all the cookies?

https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/master/Source/WebKit2/UIProcess/API/C/WKCookieManager.h

**Comment by wouterlucas** [comment]
These where added for a case when cookies stored on a server (for diskless device for example) so it's possible setting and getting all the cookies as is. Please check with your colleagues, this is a change made by you guys :)

**Comment by estobbart** [comment]
Makes sense now... thank you.
