### ISSUE TITLE
[Webinspector] Uncaught TypeError:​ document.getCSSCanvasContext is not a function (at Popover.js:​431:​37)​

### ISSUE THREAD

**Issue by vertexodessa** [WebPlatformForEmbedded/WPEWebKit#326]

**Comment by vertexodessa** [comment]
![image](https://user-images.githubusercontent.com/6557185/27950105-b8a41fa2-6308-11e7-9ede-804367833eee.png)

**Comment by jaboaty** [comment]
Its not a fix, but in the short term it seems to work on newer versions of Safari

**Comment by wouterlucas** [comment]
Fixed by b0e7fd855c5c81d307385664c8307677db1c46c9
