### ISSUE TITLE
problem with live dash stream playback

### ISSUE THREAD

**Issue by goruklu** [WebPlatformForEmbedded/WPEWebKit#331]
We noticed that live dash streams don't start playing. There seems to be a regression in Webkit as described here:
https://bugs.webkit.org/show_bug.cgi?id=170401

and on dash.js:
https://github.com/Dash-Industry-Forum/dash.js/issues/1867

A dash.js workaround is posted here:
https://github.com/Dash-Industry-Forum/dash.js/pull/1899

Here is an example stream which works on Chrome but does not start playing on Safari or WPE:
http://www.gurdal-lab.net/hao-dash-test/gurdal2.html

The following page has the work around fix in dash.js library:
http://www.gurdal-lab.net/hao-dash-test/gurdal.html

Safari can now play the above link but WPE still can't.

[Link to WPE log](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1157516/wpe_dash_live_stream_does_not_start_playback.txt)

**Comment by arunakiran-chennubhatla** [comment]
If I play the live MPEG-DASH stream 'http://irtdashreference-i.akamaihd.net/dash/live/901161/bfs/manifestARD.mpd' with the latest dash.js, it keeps repeating the same scene of 5-6 seconds forever. However if I revert the commit 'https://github.com/Dash-Industry-Forum/dash.js/pull/1899/commits/b4d6604f028da4551fbd429c9c4db418bc4fb920' and apply the below patch to dash.js, it works fine with WPE.

[Fix-for-mpeg-dash-live-with-dash-js.diff.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1302497/Fix-for-mpeg-dash-live-with-dash-js.diff.txt)

**Comment by goruklu** [comment]
We are still seeing video playback not starting with live DASH content (both clear and encrypted streams have the same issue). Dash.js v2.6 and Helio (Comcast's own DASH player) behaves the same way.

Dash.js example: http://www.gurdal-lab.net/dash.js/samples/liveDash1.html

**Comment by albertd** [comment]
@goruklu closing ticket as a lot of work has been done on wpe-2017 to get dash.js nicely working. Let me know if we need to reopen.
