### ISSUE TITLE
Encrypted content playback with EMEv1+OpenCDM+MSE does not work

### ISSUE THREAD

**Issue by goruklu** [WebPlatformForEmbedded/WPEWebKit#336]
When we try playing encrypted DASH content with MSE, the license is acquired, key is added but playback/decryption does not start. It seems like drm-session event does not reach the gstreamer decryptor instance since emitOpenCDMSession() is not implemented in MediaPlayerPrivateGstreamerMSE class.

**Comment by goruklu** [comment]
test content:
Youtube: https://yt-dash-mse-test.commondatastorage.googleapis.com/unit-tests/2016.html?&disable_log=false&test_type=encryptedmedia-test&timestamp=1495650326608&enablewebm=false&command=run&tests=17
Dash.js: http://www.gurdal-lab.net/dash.js/samples/playreadyconsec.html

**Comment by psivasubramanian** [comment]
@goruklu Just curious, which DRM by the way?

**Comment by goruklu** [comment]
@psivasubramanian we saw the same issue with both Playready and Widevine DRM
