### ISSUE TITLE
Building for Raspberry Pi 3

### ISSUE THREAD

**Issue by skerit** [WebPlatformForEmbedded/WPEWebKit#341]
I want to build WPEWebKit for my Raspberry Pi, but on my main machine.

I'm exporting `ARCHS=armv7` before doing `update-webkitwpe-libs` and `build-webkit --wpe`, but it doesn't seem to work.

Am I doing something else wrong?

**Comment by wouterlucas** [comment]
Hi @skerit I'd recommend using a build system like Buildroot or Yocto to cross compile an image on your main machine for Raspberry Pi.

Please find the buildroot repo here: https://github.com/WebPlatformForEmbedded/buildroot and the yocto repo here: https://github.com/WebPlatformForEmbedded/meta-wpe

**Comment by skerit** [comment]
Aha. I did build the entire image, and that's running fine, but I'd like to extract wpe and run it on an arch or debian image. Or does wpe rely on too many changes in other parts of the system for that to be a possibility?

**Comment by marqueeeeeee** [comment]
i'm looking for something like this too, is it possible to build only the wpeWebkit on existing raspbian image?

**Comment by wouterlucas** [comment]
@skerit yes that's possible too, just not very well documented :) I'm running WPE on my Ubuntu VM with weston/xwayland with mouse/keyboard input and works quite well. I'll try to put something together in a wiki/readme or something to share with everyone else.

@marqueeeeeee technically I guess. But it takes nearly 45 minutes while cross compiling on a Core i7, not even counting all the dependencies. Compiling that on the RPI directly will take an insane amount of time :)

**Comment by bbinet** [comment]
I would also be very interested in reading @wouterlucas wiki/readme for running wpe on raspbian.

**Comment by SteffenDE** [comment]
@wouterlucas I'd be interested too and would like to ask if there's any documentation now?

**Comment by mbardelmeijer** [comment]
Would be interested in this as well :)

**Comment by ivanskj** [comment]
also interested

**Comment by Donderda** [comment]
@wouterlucas a short(?) info about this topic would be awesome! :) 👍

**Comment by alexjstubbs** [comment]
@wouterlucas any documentation for that would be awesome 😃

**Comment by SamDecrock** [comment]
How long would an 'insane amount of time' be exactly? :D

**Comment by user8086** [comment]
I'm trying to build WPE directly on Raspbian (Stretch) image according to following instruction:
https://trac.webkit.org/wiki/WPE
There are some missing dependencies. Moreover I came across on compilation problems (at point of compiled 14% - resolved by disabling JIT option, 53% - still fighting to resolve).
Does anybody compiled WPE successfully directly on Raspbian?

**Comment by SamDecrock** [comment]
I was thinking of emulating the Pi (and therefor the ARM processor) using QEMU so that compilation is possible, but that it is way faster than building it on a real Pi.

Edit: I tried this but I can't seem to emulate more than 256MB of RAM.
