### ISSUE TITLE
Video only works on first boot

### ISSUE THREAD

**Issue by TheWizz** [WebPlatformForEmbedded/WPEWebKit#343]
I'm building for Raspberry Pi 3 using the buildroot method. It creates the image, which I can install on SD card and boot up. I run with this command

   wpe --loop http://192.168.0.20/

Works fine. I can display various web content, including video with good performance. However, now comes the strange part. Playing of video works ONLY after the first boot after imaging the SD card. If I then re-boot the Pi, displaying still images work, but as soon as I attempt to play a video using a <video> tag, the Pi locks up. No error messages in the console. The remot web debugger can no longr connect. However, I can quit wpe using Ctrl-C, and re-launch it. But this dosn't allow video to run again. I've tried turning power off for an extended period of time, and then re-try. But still no video playback. The only way I can make video play again is to re-write the card from the image file. It then works again on 1st boot.

It seems like the config somehow mutates itself after first start, stopping it from working on subsequent restarts. Any idea how to fox this or where I should start to look for what's going on?

-JM

**Comment by psivasubramanian** [comment]
@TheWizz can you try video playback second time after removing wpe cache ~/.cache/wpe instead of re flashing.

**Comment by TheWizz** [comment]
Nope, removing that folder didn't restore video playback once gone. It seemed the only notable content in it was local storage related stuff.

-JM

**Comment by psivasubramanian** [comment]
@TheWizz Ok, then it maybe a different issue. Was guessing it maybe cache related issue, but it's not. How about video playback w/o WPE?

**Comment by TheWizz** [comment]
Is there a regular browser somewhere on the WPE build that can use to try that? Or can one be installed in some straightforward manner?

-JM

**Comment by psivasubramanian** [comment]
Maybe using gst-launch utility at gstreamer level to just narrow the issue like 
$ gst-launch playbin uri=file://<path>

**Comment by TheWizz** [comment]
I'll give that a try and report back. Given that playbin takes a URI, should this also be able to play a video from a web server? That would be even closer to what I'm trying to do with WPE.

-JM

**Comment by psivasubramanian** [comment]
Yes, playbin can play it.

**Comment by TheWizz** [comment]
Hmm, gst-launch doesn't seem to be available. Is that something I need to install separately? If so, how can this be done in this constrained environment?

-JM
