### ISSUE TITLE
Youtube playback issue

### ISSUE THREAD

**Issue by psivasubramanian** [WebPlatformForEmbedded/WPEWebKit#349]
I'm using WPE browser with Yocto OE(Morty branch) based image on Dragonboard410c. I'm getting some playback error while playing the youtube streams, it plays for some time and display this message. The WPEWebkit code which my image points to is at commit [4ff934](https://github.com/WebPlatformForEmbedded/WPEWebKit/tree/4ff934a322a46bf9b42284467735ebf9e588ba29).

![img_5371](https://user-images.githubusercontent.com/18259550/29273415-cff7f430-8121-11e7-8abb-d639b33c69da.JPG)

**Comment by albertd** [comment]
@psivasubramanian is this issue still valid with the wpe-2017 branch, if so please reopen.
