### ISSUE TITLE
Web Inspector: Reloading the page does not retain focus on last selected tab and always switches back to Resource tab

### ISSUE THREAD

**Issue by Balajims88** [WebPlatformForEmbedded/WPEWebKit#362]
safari has always retain the selected tab, when we press the Reload button in web inspector.
but only WPE not retain the selected tab, always switches back to Resource tab.
Can you please confirm is it a issue or not?
if it is 'YES' , i have a potential fix.

**Comment by zak211** [comment]
Hi @Balajims88 Could you please elaborate on the issue
what rev or wpe did you see this issue?
and some clearer steps to reproduce

I am not able to reproduce the issue from the information at hand.
This is what I tried, Please correct me if I am wrong
-Boot rpi3 build (Screen shows index.html)
-Open web inspecter from webkitbrowser tab
-Go to console tab
-refresh page
-There is a refresh button inside the webinspector as well
And notice that the console tab is retained

**Comment by Balajims88** [comment]
@zak211 @wouterlucas can you please port the below commit to metro master and stable. Comcast is in need of this fix.
https://github.com/WebKit/webkit/commit/01b105062642e4ff9e833f96505a8c37591f0166

**Comment by wouterlucas** [comment]
Cherry-picked to stable, fix is already in master since that just received an upstream merge.

**Comment by Balajims88** [comment]
Thanks Wouterlucas
