### ISSUE TITLE
[EMEV1] Unable to play widevine content with both Audio and Video encrypted

### ISSUE THREAD

**Issue by pavankn** [WebPlatformForEmbedded/WPEWebKit#378]
Hi Experts, 
I am unable to play a content with both Audio and video encrypted (mp4 cenc encryption) which is generated through Shaka packager . The content is being played through Dash.Js player . 

The behavior is like follows : 
1. Only single CDMSession got emitted (Even though both the tracks are encrypted)
2. generateKeyRequest and addKey called only once for video track 
3. When i run through DashJs, audio decryption is proper throughout the duration while video fails to get decrypted (macroblocks after initial 10 sec)

Let me know if there is a change which i am missing for EMEV1 .

Thanks
Pavan

**Comment by albertd** [comment]
EMEv1 is not supported any more, we've moved to EMEv3 on wpe-2017 branch
