### ISSUE TITLE
IndexedDB: IDBFactory.open should be delayed if there is a pending delete request (+race condition with Web Inspector)

### ISSUE THREAD

**Issue by vertexodessa** [WebPlatformForEmbedded/WPEWebKit#386]
According to https://www.w3.org/TR/IndexedDB/, 
`Databases has a delete pending flag which is used during deletion. When a database is requested to be deleted the flag is set to true and all attempts at opening the database are stalled until the database can be deleted.` 

Even if a user does not call IDBFactory.open during the delete request from JavaScript, this brings a race condition when Web Inspector can execute IDBFactory::open while loading webpage that deletes the database:
https://github.com/WebKit/webkit/blob/master/Source/WebCore/inspector/InspectorIndexedDBAgent.cpp#L158

**Comment by vertexodessa** [comment]
Test case (fails 100% of the time in my setup): https://gist.github.com/vertexodessa/7b327a23ad37ed4dc1dab49c494ef203

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
