### ISSUE TITLE
Video plays in a small rectangle instead of full screen

### ISSUE THREAD

**Issue by vanihegde** [WebPlatformForEmbedded/WPEWebKit#408]
When we start playing a channel from SlingTV app, the video starts as a small rectangle in the middle of the screen. 

The app is found at http://bff.movetv.com/develop
login: sling2@comcast.com
password: 0000

Play the "DIY" channel, other channels are encrypted and will not play yet.
Reproducible with revision b22045fe49277f0121dfeac1c15439d209022c6e of stable branch.

--------------------------------------
Few points to note:
1) This issue happens only when **accelerated compositing is disabled** for the video tag (attaching the patch that we used to achieve this).
2) Video starts playing in fullscreen very rarely after sometime (I am guessing only if some kind of repaint is triggered). For example, start playing the video and then click on 'Show Compositing Borders' from the web inspector, video goes to fullscreen immediately.
3) You may have to enable local storage for this page.
4) Looks like a lot of page elements are added dynamically through JS.
5) I am still trying to reproduce this issue with a simpler page.

[disableACForVideoPatch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1475593/disableACForVideoPatch.txt)

**Comment by vanihegde** [comment]
Forgot to mention, you will have to try this on a box with full Comcast software stack on it.

**Comment by albertd** [comment]
@vanihegde is this is still the case using wpe-2017 branch?
