### ISSUE TITLE
GStreamer-CRITICAL Error with youtube live video

### ISSUE THREAD

**Issue by samouds** [WebPlatformForEmbedded/WPEWebKit#411]
Hello,

I'm trying the [resin-wpe](https://github.com/resin-io-playground/resin-wpe) project (which uses WPEWebKit) with a RPi3 to display a live video from youtube : https://www.youtube.com/embed/hL0sEdVJs3U?autoplay=1&vq=hd720

But the video won't start and I get this error :

```
(WPEWebProcess:39): GStreamer-CRITICAL **: _gst_util_uint64_scale: assertion 'denom != 0' failed
```

And it works fine with a normal video from youtube.

Any idea ?

Thanks.

**Comment by eocanha** [comment]
You need a patched GStreamer to solve this issue. It's solved in WebKit upstream here:
https://bugs.webkit.org/show_bug.cgi?id=176804

I've just backported the patch to gst1-plugins-good in buildroot here:
https://github.com/WebPlatformForEmbedded/buildroot/commit/85e8095885508609549ded9c5178443cac1a492c

**Comment by samouds** [comment]
Thanks, is this already patched in https://github.com/WebPlatformForEmbedded/meta-wpe ?

**Comment by eocanha** [comment]
I don't think so. I usually work only with buildroot. Maybe @wouterlucas can port the patch to that repo.

**Comment by wouterlucas** [comment]
Done! https://github.com/WebPlatformForEmbedded/meta-wpe/commit/bb6d3bbf21cb071dbec227ebb69954b70b63c3e2

**Comment by samouds** [comment]
Thanks @wouterlucas  and @eocanha 

When I try to build a new image with meta-wpe I get this error : 

```
| checking for cairo’s EGL functions feature…
| checking whether cairo’s EGL functions feature could be enabled… no (not required by any backend)
| configure: error: EGL functions feature could not be enabled
| NOTE: The following config.log files may provide further information.
| NOTE: /home/samoud/resin-wpe/base-image/build/tmp-glibc/work/cortexa7hf-neon-vfpv4-oe-linux-gnueabi/cairo/1.14.10-r0/build/config.log
| ERROR: configure failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /home/samoud/resin-wpe/base-image/build/tmp-glibc/work/cortexa7hf-neon-vfpv4-oe-linux-gnueabi/cairo/1.14.10-r0/temp/log.do_configure.31984)
ERROR: Task (/home/samoud/resin-wpe/base-image/build/…/poky/meta/recipes-graphics/cairo/cairo_1.14.10.bb:do_configure) failed with exit code '1’
NOTE: Tasks Summary: Attempted 1294 tasks of which 1253 didn’t need to be rerun and 1 failed.
```

**Comment by wouterlucas** [comment]
Try adding this to your local conf:
DISTRO_FEATURES_remove = "x11"
DISTRO_FEATURES_append = " opengl"

If you have further build issues lets handle them in the meta-wpe issue tracker.

**Comment by samouds** [comment]
Ok @wouterlucas  thanks !
