### ISSUE TITLE
how to find FPS

### ISSUE THREAD

**Issue by karora123** [WebPlatformForEmbedded/WPEWebKit#412]
Hi,

Is there any way to calculate Frame Per Second for video rendering using WPELauncher.

**Comment by magomez** [comment]
You can use the enviroment variable WEBKIT_SHOW_FPS=1 and it will show the frames per second in the top left corner of the screen while playing.

**Comment by karora123** [comment]
Hi...thanks for quick response...I shall give it a try....well, what about if I need to calculate FPS for any application rendering using westeros compositor? Is there any utility for compositor specific?

**Comment by karora123** [comment]
To make use of WPEKIT_SHOW_FPS it seems WebCore should be reconfigured with texmap subdirectory. Any idea what source files I should append to make use of FPS display or It needs to append every source file?

**Comment by karora123** [comment]
Hi,
WebCore/CMakefile.txt I have enabled following files in order to get FPS window at top left of rendering screen. I have setup the given flag still not able to see any FPS window. Any idea if I missed out any?

 platform/graphics/texmap/TextureMapper.cpp
    platform/graphics/texmap/TextureMapperGL.cpp
    platform/graphics/texmap/TextureMapperLayer.cpp
    platform/graphics/texmap/TextureMapperAnimation.cpp
    platform/graphics/texmap/TextureMapperFPSCounter.cpp
    platform/graphics/texmap/TextureMapperShaderProgram.cpp
    platform/graphics/texmap/TextureMapperSurfaceBackingStore.cpp
    platform/graphics/texmap/TextureMapperBackingStore.cpp
    platform/graphics/texmap/TextureMapperPlatformLayerBuffer.cpp
    platform/graphics/texmap/TextureMapperPlatformLayerProxy.cpp

**Comment by magomez** [comment]
How is it that you were using WPE without enabling the TextureMapper?
I'm not sure which config you're using but, unless you have implemented it yourself, running WPE without the TextureMapper is not possible... maybe it doesn't crash, but it's not going to display anything.

Regarding the FPS question, there's no specific way for apps to get the FPS other than calculating it themselves, usually counting the number of requestAnimationFrame() calls processed.

**Comment by magomez** [comment]
Actually requestAnimationFrame() will cap at 60fps... if you want to count framerates bigger than than that you should use setTimeout(0) instead.

**Comment by karora123** [comment]
Hi, Thanks for update !! few queries:-

1. How to enable Text Mapper? I just have enabled in WebCore Makefile and appended set of files as source file given above post. Still I could able to play WPELauncher and youtube tv app. Rendering video but not able to view FPS..is there anything I left? By default TextMapper is disable in my release and did not see any failure while rendering video.

2. requestAnimationFrame() counting the calls of this APIs from Wpewebkit will give some idea?

**Comment by albertd** [comment]
@karora123 FPS is visible in the web console of wpe framework
