### ISSUE TITLE
Webkit Remote inspector not accessible (yocto)

### ISSUE THREAD

**Issue by samouds** [WebPlatformForEmbedded/WPEWebKit#417]
Hello,

I'm trying to access the remote webkit inspector on my wpe yocto image (with wpe-webkit-web-inspector-plugin added to IMAGE_INSTALL)

But when I set the env var WEBKIT_INSPECTOR_SERVER and try to access the address on my browser I get this error : 
```
Error: 0, The resource at Ã¢Â€Âœ/org/wpe/inspector/UserInterface/inspectorPageIndex.htmlÃ¢Â€Â does not exist occurred during fetching inspector resource files.
```

Any idea ?

**Comment by nveljkovic** [comment]
If you are at the newest version of WPEWebkit code (last month), you might have more luck with exporting:
WEBKIT_LEGACY_INSPECTOR_SERVER

**Comment by samouds** [comment]
@nveljkovic thx but it didn't work.
