### ISSUE TITLE
WebKIt Remote Inspector javascript error

### ISSUE THREAD

**Issue by mnatasa** [WebPlatformForEmbedded/WPEWebKit#418]
Hello,

I'm using Web Inspector but there is a problem to expand HTML elements. When I click on some element nothing happens and in console I get following error:

`URLUtilities.js:101 Uncaught SyntaxError: Invalid regular expression: /^(?<scheme>[^\/:]+):\/\/(?<host>[^\/#:]*)(?::(?<port>[\d]+))?(?:(?<path>\/[^#]*)?(?:#(?<fragment>.*))?)?$/: Invalid group
    at parseURL (URLUtilities.js:101)
    at handleUncaughtException (UncaughtExceptionReporter.js:67)`

This is my environment:
OS: Ubuntu 16.04 (64-bit)
Connecting to remote inspector via Chrome (version 62, 64-bit)
Branch: master

**Comment by albertd** [comment]
Not sure this is still an issue, closing for now.
