### ISSUE TITLE
Low frame rate on WPEBrowser

### ISSUE THREAD

**Issue by karora123** [WebPlatformForEmbedded/WPEWebKit#421]
Hi,
Observed low frame rate using WPE Browser whereas GPU enabled & all essential graphics supporting components are also working in the RPI setup.  Tried generic link as "https://testdrive-archive.azurewebsites.net/performance/fishietank/" and "http://themaninblue.com/experiment/AnimationBenchmark/canvas/" to benchmark FPS on RPI, seems just 2 or 3 FPS in first case & 10 to 15 in another whereas same worked on raspbian image with 20 FPS & 35 respectively. Is the diff is expected in WPEbrowser case?
I have used core minimal poky image having WPE/Westeros enabled.
Is there any known issue at backend side for low FPS?

**Comment by wouterlucas** [comment]
Compared to what? which browser is giving you 20 to 35? I know with WPE Canvas isn't the strongest suite due to the Ciaro rendering path, we're a lot better on the WebGL performance part. Did you try and compare that too?

**Comment by karora123** [comment]
Hi Wouter,
Good to see you !!
I tried over default raspbian browser which is chromium after enabling openGL with full KMS support.
Is there any way or test case present to test WebGL?

**Comment by karora123** [comment]
Hi Wouter,

I have tried open links for WebGL content testing using WPE as below:-
http://www.webglearth.com/#ll=46.59079,11.68484;alt=12599;t=-0.192
https://sketchfab.com/
http://www.webgl-publisher.com/

Contents not able to download successfully, same behavior observed in all three cases.

**Comment by cztomsik** [comment]
There's probably some other problem, this is from my macbook with i7 and hd graphics (which generally accelerates well, I've also tried in Safari and it was 60fps)

![image](https://user-images.githubusercontent.com/3526922/38174614-3254e67a-35d0-11e8-9cd0-0788ca1aa116.png)

**Comment by SamDecrock** [comment]
Just built WPE with buildroot and running on Pi3: I too can't load the fishtank. It just shows a blank page. I'll try to figure out what's wrong.

**Comment by albertd** [comment]
@SamDecrock just validated on my build and it was working, but slow performance as stated above, the refactor of the graphics engine will hopefully solve the canvas2d performance in the near future. I would recommend using webgl, as that is extremely fast.
