### ISSUE TITLE
Memory pressure settings is not working

### ISSUE THREAD

**Issue by nikolaKnezevic** [WebPlatformForEmbedded/WPEWebKit#424]
Hi, I'm trying to limit wpe's memory usage by setting env. var. WPE_POLL_MAX_MEMORY.
But the file where that var. is read is not compiling at all (WebCore/platform/linux/MemoryPressureHandlerLinux.cpp).
I can see that in webkit upstream that file is moved to WTF/wtf/linux/MemoryPressureHandlerLinux.cpp.
But in this repository these files regarding memory pressure are left in WebCore module, and it is building upstream files from WTF module.
- WTF/wtf/MemoryPressureHandler.h
- WTF/wtf/MemoryPressureHandler.cpp
- WTF/wtf/linux/MemoryPressureHandlerLinux.cpp

branch is master.

**Comment by eocanha** [comment]
Thank you for reporting. The MemoryPressureHandler has been restored to its usual behaviour in https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/5a96512b411159c1a820cd191e6b8cbd3b083ffc
