### ISSUE TITLE
Webprocess is hanged (Deadlock) in parkConditionallyImpl

### ISSUE THREAD

**Issue by nambirajang** [WebPlatformForEmbedded/WPEWebKit#430]
We are seeing  WebProcess hang in stable WPE version. 
This hang is because of deadlock  in parkConditionallyImpl.

Frame | Signature | Module | Source
-- | -- | -- | --
#0 | libpthread-2.19.so@0xedc6 | libpthread-2.19.so |  
#1 | libpthread-2.19.so@0x9bdd | libpthread-2.19.so |  
#2 | libpthread-2.19.so@0x9947 | libpthread-2.19.so |  
#3 | timedWait | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:359 (0x7)
#4 | parkConditionallyImpl | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WTF/wtf/ParkingLot.cpp:598 (0xd)
#5 | performTaskSync | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WTF/wtf/ParkingLot.h:85 (0x3)
#6 | setViewportSize | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WebKit2/Shared/CoordinatedGraphics/threadedcompositor/ThreadedCompositor.cpp:149 (0x3)
#7 | contentsSizeChanged | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WebKit2/WebProcess/WebPage/CoordinatedGraphics/ThreadedCoordinatedLayerTreeHost.cpp:100 (0x13)
#8 | handleMessage<Messages::DrawingArea::UpdateBackingStoreState, WebKit::DrawingArea, void (WebKit::DrawingArea::*)(long long unsigned int, bool, float, const WebCore::IntSize&, const WebCore::IntSize&)> | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WebKit2/Platform/IPC/HandleMessage.h:40 (0x27)
#9 | didReceiveMessage | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/build/DerivedSources/WebKit2/DrawingAreaMessageReceiver.cpp:61 (0x19)
#10 | dispatchMessage | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WebKit2/Platform/IPC/MessageReceiverMap.cpp:123 (0x9)
#11 | didReceiveMessage | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WebKit2/WebProcess/WebProcess.cpp:641 (0x3)
#12 | dispatchMessage | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WebKit2/Platform/IPC/Connection.cpp:893 (0xb)
#13 | dispatchOneMessage | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WebKit2/Platform/IPC/Connection.cpp:951 (0x3)
#14 | performWork | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WTF/wtf/Function.h:50 (0x7)
#15 | _FUN | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:66 (0x3)
#16 | g_main_context_dispatch | libglib-2.0.so.0.4800.1 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:3154 (0x3)
#17 | g_main_context_iterate | libglib-2.0.so.0.4800.1 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:3840 (0x5)
#18 | g_main_loop_run | libglib-2.0.so.0.4800.1 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:4034 (0x9)
#19 | run | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:97 (0x5)
#20 | ChildProcessMain<WebKit::WebProcess, WebKit::WebProcessMain> | libWPEWebKit.so.0.0.20161117 | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WebKit2/Shared/unix/ChildProcessMain.h:61 (0x3)
#21 | main | WPEWebProcess | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WebKit2/WebProcess/EntryPoint/unix/WebProcessMain.cpp:52 (0x7)
#22 | libc-2.19.so@0x16337 | libc-2.19.so |  
#23 | google_breakpad::TypedMDRVA<MDString>::AllocateObjectAndArray | WPEWebProcess | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/breakpad/svn-r0/trunk/./src/client/minidump_file_writer-inl.h:66 (0x17)
#24 | libc-2.19.so@0xf4ffe | libc-2.19.so |  
#25 | ConvertUTF8toUTF32 | WPEWebProcess | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/breakpad/svn-r0/trunk/src/common/convert_UTF.c:484 (0xf)
#26 | main | WPEWebProcess | /mnt/jenkins/workspace/CXD01ANI-Yocto-Release/build-ciscoxid/tmp/work/cortexa15t2hf-vfp-neon-rdk-linux-gnueabi/wpe-webkit/0.2+gitAUTOINC+5c0c3fd0aa-r0/git/Source/WebKit2/WebProcess/EntryPoint/unix/WebProcessMain.cpp:53 (0x35)

**Comment by nambirajang** [comment]
[](url)
[Trace1.docx](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1635347/Trace1.docx)
[Trace2.docx](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/1635349/Trace2.docx)

**Comment by albertd** [comment]
@nambirajang is this issue still valid with the wpe-2017 branch, if so can you supply a bit more details so we can reopen if needed.
