### ISSUE TITLE
Quota exceeded error

### ISSUE THREAD

**Issue by SteffenDE** [WebPlatformForEmbedded/WPEWebKit#431]
I'm trying to use a webpage that uses [PouchDB](https://pouchdb.com/) to manage some of its state. In Webkit browsers WebSQL is used as storage backend, but in WPE I get the following error:
`Unhandled promise rejection {"status":500,"name":"web_sql_went_bad","message":"unknown","reason":"The quota has been exceeded."}`.
I tested this using [buildroot](https://github.com/WebPlatformForEmbedded/buildroot) and [yocto](https://github.com/WebPlatformForEmbedded/meta-wpe), but it's always the same error. Is this something which is known or why do you think this happens?
Device: Raspberry Pi 3 (buildroot master branch/meta-wpe master branch).

To reproduce: https://codepen.io/anon/pen/xpXRab
Try this in Chrome/Firefox/Safari and you should see something like `{ "ok": true, "id": "testdoc", "rev": "1-58db569cc5fa4ea6b4ffe989a457c07a" } `, but in WPE I get the quota error from above.

Thanks for any help!

To make sure that enough disk space is left:
```bash
root@raspberrypi3:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root               406.5M    236.1M    148.9M  61% /
devtmpfs                300.6M         0    300.6M   0% /dev
tmpfs                   305.1M    136.0K    304.9M   0% /run
tmpfs                   305.1M    248.0K    304.8M   0% /var/volatile
```

**Comment by SteffenDE** [comment]
https://codepen.io/anon/pen/Eowroz tests if opening a WebSQL database works. Same error as above.

**Comment by SteffenDE** [comment]
IndexedDB works as expected, saving database files to `/root/.local/share/wpe/databases/indexeddb/` so this seems to be an error with WebSQL only.

**Comment by wouterlucas** [comment]
Ahhn my bad, I don't think WebSQL is supported at all in WebKit. It's an abandoned spec at W3, last update is nov 2010. The spec is, as far as I understand, superseded by IndexedDB support. Also doesn't seem to work on my Safari.

Is there any reason you are looking for WebSQL support in particular?

**Comment by SteffenDE** [comment]
WebSQL does work in Webkit, at least in Safari on macOS.
The reason is that PouchDB is using WebSQL in Webkit based browsers (like Safari) because the IndexedDB implementation wasn't working correctly in previous versions. They want to change [this](https://github.com/pouchdb/pouchdb/issues/6943) soon, but currently my project doesn't work in WPE because WebSQL support **is advertised**, but it just doesn't work.

![html5test.com using WPE](https://s3.eu-central-1.amazonaws.com/steffend/public/IMG_6665.jpg)

> Also doesn't seem to work on my Safari.

You're not getting the quota error, are you? I'm getting err 18 (SecurityError), but that seems to be because of some Safari privacy settings (Codepen runs the code in an iframe). Try opening the page [directly](https://s.codepen.io/boomerang/iFrameKey-75480ffd-a3f2-d202-01a2-667110fcdbbb/index.html). This should display `true`.

**Comment by wouterlucas** [comment]
Interesting, I tried that link you've shared earlier on Safari nightly and that didn't work. The html5 test indeed show the same as your screenshot. 

Quick search shows there are indeed bits and pieces of WebSQL in the WPE code tree. We could see if there is a flag to enable it, but you're boldly going where no man has gone before on WPE :)

**Comment by SteffenDE** [comment]
Well I think it would be nice to have the same support for WebSQL as in Safari, but it wouldn't be bad if there was no support at all. The main problem is that WPE shouldn't expose any WebSQL APIs if they don't work.

**Comment by albertd** [comment]
@SteffenDE in the latest wpe-2017 WebSQL and IndexedDB should be properly supported. Closing ticket for now.
