### ISSUE TITLE
Youtube video not playing

### ISSUE THREAD

**Issue by aazamansari** [WebPlatformForEmbedded/WPEWebKit#438]
Current logic for calculating Buffered() range in MediaSource uses PTS values for calculating the range.
As per MSE spec we are supposed to use PTS to calculate Range. But this logic for calculating range does not work if the video framerate is <=6.

This is generally observed on youtube videos with framerate <=6.
Below are couple of links used to reproduce the issue.
https://www.youtube.com/tv?launch=menu#/watch/video/idle?v=lsZG7n7ries&list=PLNY8MNJWsu4NWiCJmcluShap0L0JhmEVU&resume
https://www.youtube.com/tv#/watch/video/control?v=1RXeXJXheIA&list=PLqWu2z6lBLzUuQg8Gvtgvb_0pO2IAEUQO&resume

In chromium the logic to calculate range is changed from using PTS to DTS.

Below is the chromium bug that was used to fix the issue in chromium.
https://bugs.chromium.org/p/chromium/issues/detail?id=718641

**Comment by albertd** [comment]
@aazamansari I think this has been resolved with the latest wpe-2017 branch, please reopen if needed.
