### ISSUE TITLE
xkbcommon: ERROR: couldn't find a Compose file for locale "C"

### ISSUE THREAD

**Issue by Yaro96** [WebPlatformForEmbedded/WPEWebKit#440]
After a successufull build I can't start the wpe:
`yaroslav@ubuntu:~/WPEWebKit$ WAYLAND_DISPLAY=wpe Tools/Scripts/run-minibrowser --wpe`
`Starting dyz `
`xkbcommon: ERROR: couldn't find a Compose file for locale "C"`

Any suggestions?

**Comment by shi-yan** [comment]
I saw the same issue, how did you fix this?

**Comment by nveljkovic** [comment]
@shi-yan , this is just a benign warning, issue is probably something else. Try running browser with additional logging.

**Comment by wouterlucas** [comment]
Usually means you are missing xkeyboard-config package (at least a that's what its called in OE). That makes sure you have the locales installed.

How did you build wpewebkit?

**Comment by bramoosterhuis** [comment]
This is basically just a warning that a mappings for multi-key input sequences is not found. If you want to silence it you can set XCOMPOSEFILE to an empty file.  Offcoarce you drop support for the multi-key input sequences

```
touch /tmp/compose
export XCOMPOSEFILE=/tmp/compose
```

**Comment by shi-yan** [comment]
I think the locale folder as in /usr/shared/X11/ comes from the package libx11-data, not keyboard-config

**Comment by amancapy** [comment]
It's been a while but have you found a solution? I still get 

```
xkbcommon: ERROR: Couldn't read Compose file /tmp/compose: Invalid argument
```
