### ISSUE TITLE
WPE behind proxy

### ISSUE THREAD

**Issue by Yaro96** [WebPlatformForEmbedded/WPEWebKit#441]
Is it posssible to use wpe behind a proxy?
It works quite well with web pages from the local network, but it doesn't use the system proxy to be able to go on the Internet

**Comment by albertd** [comment]
Yes you can, we're parsing the /boot/proxy file for the settings during startup:

https://github.com/WebPlatformForEmbedded/buildroot/blob/master/package/wpe/wpeframework/S80WPEFramework#L41-L48
