### ISSUE TITLE
Error at Tools/Scripts/update-webkitwpe-libs command, when execute it

### ISSUE THREAD

**Issue by setonelf** [WebPlatformForEmbedded/WPEWebKit#446]
Appears this error:

*** Checking out xkbcommon *** [12/31]
wget --continue http://pkgs.fedoraproject.org/repo/pkgs/libxkbcommon/libxkbcommon-0.5.0.tar.xz/2e1faeafcc609c30af3a561a91e84158/libxkbcommon-0.5.0.tar.xz -O /home/certi/.cache/jhbuild/downloads/libxkbcommon-0.5.0.tar.xz
--2018-02-21 13:53:52--  http://pkgs.fedoraproject.org/repo/pkgs/libxkbcommon/libxkbcommon-0.5.0.tar.xz/2e1faeafcc609c30af3a561a91e84158/libxkbcommon-0.5.0.tar.xz
Resolvendo pkgs.fedoraproject.org (pkgs.fedoraproject.org)... 209.132.181.4
Conectando-se a pkgs.fedoraproject.org (pkgs.fedoraproject.org)|209.132.181.4|:80... conectado.
A requisição HTTP foi enviada, aguardando resposta... 403 Forbidden
2018-02-21 13:53:53 ERRO 403: Forbidden.

Failed to build WPE port dependencies with jhbuild

**Comment by marcw** [comment]
I got the same.

**Comment by freesamael** [comment]
Looks like the link was changed in [commit 8fa5e57](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/8fa5e577527b455e4eeef32a898df2dd4cf87983). I'm not sure what certificate problem mentioned in the commit message was, but maybe it no longer stands. Changing it back to xkbcommon.org works for me.

**Comment by calvaris** [comment]
This repository is to be used with buildroot or yocto. Jhbuild is now deprecated.
