### ISSUE TITLE
Upstream JPEG encoding

### ISSUE THREAD

**Issue by cadubentzen** [WebPlatformForEmbedded/WPEWebKit#447]
This fork has JPEG encoding, allowing canvas exporting to JPEG, which was added in 250fd86.

However, WPE upstream only exports to PNG. Have you tried upstreaming this commit or is there a reason not to?

There is a bug open: https://bugs.webkit.org/show_bug.cgi?id=180352

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
