### ISSUE TITLE
QNX Port

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [WebPlatformForEmbedded/WPEWebKit#453]
Is anyone aware of a QNX 6.x or 700 port, or any work being done on it?

I started looking at a basic 700 port.  It doesn't look too bad.

Thanks,
Joel

**Comment by INRIX-joel-winarske** [comment]
Worked through building all the dependent libs (many), and am into WPEWebKit WTF.

    Source/WTF/wtf/StackBounds.cpp:101:38: error: 'pthread_getattr_np' was not declared in this scope
         pthread_getattr_np(thread, &sattr);
                                          ^

Non-portable (np) pthread calls are not available with QNX pthread.  So for QNX this routine needs a portable solution.  We may need to pass the attribute to the thread function.

The code comment states:

    // FIXME: this function is non-portable; other POSIX systems may have different np alternatives

**Comment by charlie-ht** [comment]
There did used to be some QNX support. You might find some inspiration in this old ticket: https://bugs.webkit.org/show_bug.cgi?id=27885 or possible in an old version of StackBounds when QNX was supported (note the API changes though!) https://github.com/adobe/webkit/blob/master/Source/WTF/wtf/StackBounds.cpphttps://github.com/adobe/webkit/blob/master/Source/WTF/wtf/StackBounds.cpp

However, this would be better discussed upstream if you're working towards a new QNX port.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
