### ISSUE TITLE
build errors on master with the latest WPEOpenCDM

### ISSUE THREAD

**Issue by enioc** [WebPlatformForEmbedded/WPEWebKit#457]
Building with -DENABLE_ENCRYPTED_MEDIA=ON and -DENABLE_OPENCDM=ON on master branch:
[c2c6af6](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/c2c6af6af012ed034df207f50a825b6a156a23fb),
I got an error as the following:

> In file included from Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp:63:0:
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.h: In member function 'media::OpenCdm::KeyStatus WebCore::CDMInstanceOpenCDM::Session::update(const uint8_t*, uint16_t, std::__cxx11::string&)':
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.h:74:165: error: invalid conversion from 'const uint8_t* {aka const unsigned char*}' to 'unsigned char*' [-fpermissive]
         media::OpenCdm::KeyStatus update(const uint8_t* data, const uint16_t length, std::string& response) { m_lastStatus = m_session.Update(data, length, response); return m_lastStatus; }
                                                                                                                                                                     ^
In file included from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.h:32:0,
                 from Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp:63:
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:93:13: note:   initializing argument 1 of 'media::OpenCdm::KeyStatus media::OpenCdm::Update(unsigned char*, int, std::__cxx11::string&)'
   KeyStatus Update(unsigned char*, int, std::string&);
             ^
[3624/4511] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/WebKitWebSourceGStreamer.cpp.o
ninja: build stopped: subcommand failed.

And I shifted media::OpenCdm::Update function in CDMOpenCDM.h, it passed but more errors occured:

> from Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp:23:
arm-linux-gnueabihf/include/c++/5.3.1/bits/unique_ptr.h: In instantiation of 'typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = media::OpenCdm; _Args = {const char*}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<media::OpenCdm>]':
Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp:110:93:   required from here
arm-linux-gnueabihf/include/c++/5.3.1/bits/unique_ptr.h:765:69: error: no matching function for call to 'media::OpenCdm::OpenCdm(const char*)'
     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
                                                                     ^
> In file included from Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp:30:0:
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:64:3: note: candidate: media::OpenCdm::OpenCdm()
   OpenCdm();
   ^
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:64:3: note:   candidate expects 0 arguments, 1 provided
[6/891] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp.o
FAILED: Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp.o

> Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp: In member function 'virtual bool WebCore::CDMPrivateOpenCDM::supportsConfiguration(const MediaKeySystemConfiguration&) const':
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:81:115: error: passing 'const media::OpenCdm' as 'this' argument discards qualifiers [-fpermissive]
         if (!m_openCDM.IsTypeSupported(m_openCDMKeySystem.utf8().data(), audioCapability.contentType.utf8().data()))
                                                                                                                   ^
> In file included from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.h:32:0,
                 from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:24:
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:101:8: note:   in call to 'bool media::OpenCdm::IsTypeSupported(const string&, const string&)'
   bool IsTypeSupported(const  std::string& keySystem,const  std::string& mimeType);
        ^
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:84:115: error: passing 'const media::OpenCdm' as 'this' argument discards qualifiers [-fpermissive]
         if (!m_openCDM.IsTypeSupported(m_openCDMKeySystem.utf8().data(), videoCapability.contentType.utf8().data()))
                                                                                                                   ^
> In file included from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.h:32:0,
                 from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:24:
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:101:8: note:   in call to 'bool media::OpenCdm::IsTypeSupported(const string&, const string&)'
   bool IsTypeSupported(const  std::string& keySystem,const  std::string& mimeType);
        ^
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp: In constructor 'WebCore::CDMInstanceOpenCDM::Session::Session(const media::OpenCdm&, WTF::Ref<WebCore::SharedBuffer>&&)':
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:197:35: error: use of deleted function 'media::OpenCdm::OpenCdm(const media::OpenCdm&)'
     , m_initData(WTFMove(initData))
                                   ^
In file included from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.h:32:0,
                 from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:24:
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:42:7: note: 'media::OpenCdm::OpenCdm(const media::OpenCdm&)' is implicitly deleted because the default definition would be ill-formed:
 class OpenCdm : public media::OpenCdmPlatformComCallbackReceiver {
       ^
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:42:7: error: use of deleted function 'std::mutex::mutex(const std::mutex&)'
In file included from Source/WTF/wtf/HashTable.h:26:0,
                 from Source/WTF/wtf/HashSet.h:26,
                 from Source/WebCore/platform/encryptedmedia/CDMRestrictions.h:30,
                 from Source/WebCore/Modules/encryptedmedia/MediaKeysRestrictions.h:30,
                 from Source/WebCore/Modules/encryptedmedia/CDM.h:34,
                 from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.h:27,
                 from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:24:
arm-linux-gnueabihf/include/c++/5.3.1/mutex:129:5: note: declared here
     mutex(const mutex&) = delete;
     ^
In file included from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.h:32:0,
                 from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:24:
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:42:7: error: use of deleted function 'std::condition_variable::condition_variable(const std::condition_variable&)'
 class OpenCdm : public media::OpenCdmPlatformComCallbackReceiver {
       ^
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:21:0,
                 from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.h:32,
                 from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:24:
arm-linux-gnueabihf/include/c++/5.3.1/condition_variable:81:5: note: declared here
     condition_variable(const condition_variable&) = delete;
     ^
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:202:72: error: no matching function for call to 'media::OpenCdm::GetKeyMessage(std::__cxx11::string&, uint8_t [1024], uint16_t&)'
     m_session.GetKeyMessage(m_message, temporaryURL, temporaryURLLength);
                                                                        ^
In file included from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.h:32:0,
                 from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:24:
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:90:8: note: candidate: void media::OpenCdm::GetKeyMessage(std::__cxx11::string&, int*, unsigned char*, int*)
   void GetKeyMessage(std::string&, int*, unsigned char*, int*);
        ^
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:90:8: note:   candidate expects 4 arguments, 3 provided
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp: In constructor 'WebCore::CDMInstanceOpenCDM::CDMInstanceOpenCDM(media::OpenCdm&, const WTF::String&)':
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:223:28: error: use of deleted function 'media::OpenCdm::OpenCdm(const media::OpenCdm&)'
     , m_keySystem(keySystem)
                            ^
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp: In member function 'virtual void WebCore::CDMInstanceOpenCDM::requestLicense(WebCore::CDMInstance::LicenseType, const WTF::AtomicString&, WTF::Ref<WebCore::SharedBuffer>&&, WebCore::CDMInstance::LicenseCallback)':
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:244:37: error: use of deleted function 'media::OpenCdm::OpenCdm(const media::OpenCdm&)'
     media::OpenCdm openCDM(m_openCDM);
                                     ^
Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:246:152: error: no matching function for call to 'media::OpenCdm::CreateSession(const char*&, const uint8_t*, size_t, media::OpenCdm::LicenseType)'
     sessionId = openCDM.CreateSession(m_mimeType, reinterpret_cast<const uint8_t*>(initData->data()), initData->size(), openCDMLicenseType(licenseType));
                                                                                                                                                        ^
In file included from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.h:32:0,
                 from Source/WebCore/platform/graphics/gstreamer/eme/CDMOpenCDM.cpp:24:
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:89:8: note: candidate: bool media::OpenCdm::CreateSession(const string&, unsigned char*, int, std::__cxx11::string&, media::OpenCdm::LicenseType)
   bool CreateSession(const std::string& ,unsigned char* , int, std::string&, LicenseType);
        ^
arm-buildroot-linux-gnueabihf/sysroot/usr/include/opencdm/open_cdm.h:89:8: note:   candidate expects 5 arguments, 4 provided
[13/891] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp.o
In file included from Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:136:0:
arm-buildroot-linux-gnueabihf/sysroot/usr/include/cairo/cairo-gl.h:65:5: warning: "CAIRO_HAS_GL_SURFACE" is not defined [-Wundef]
 #if CAIRO_HAS_GL_SURFACE || CAIRO_HAS_GLESV2_SURFACE
     ^
arm-buildroot-linux-gnueabihf/sysroot/usr/include/cairo/cairo-gl.h:95:5: warning: "CAIRO_HAS_GLX_FUNCTIONS" is not defined [-Wundef]
 #if CAIRO_HAS_GLX_FUNCTIONS
     ^
arm-buildroot-linux-gnueabihf/sysroot/usr/include/cairo/cairo-gl.h:113:5: warning: "CAIRO_HAS_WGL_FUNCTIONS" is not defined [-Wundef]
 #if CAIRO_HAS_WGL_FUNCTIONS
     ^
ninja: build stopped: subcommand failed.

The version of WPEOpenCdm: [wpe](https://github.com/WebPlatformForEmbedded/WPEOpenCDM):[d805ed3](https://github.com/WebPlatformForEmbedded/WPEOpenCDM/commit/d805ed3e7035c8cdf13ccfa7febbd17f08021660)

**Comment by charlie-ht** [comment]
We're in a transition phase to move away from WPEOpenCDM to an alternative implementation (which is not yet available publicly), the goal was to maintain interface interop in the meantime, but we don't test with WPEOpenCDM anymore and can't support issues relating to it. Sorry for that not being clear.

**Comment by enioc** [comment]
Do you have any release plan for the new implementation to replace the legacy WPEOpenCDM? 
Since we were trying EMEv3 on WPEWebKit but got that it was still not working until now,
we got to know when and how we can get it working.

**Comment by charlie-ht** [comment]
There is no release plan.
