### ISSUE TITLE
Can WPE support multiple threads to handle WEB-GL

### ISSUE THREAD

**Issue by deeps8us** [WebPlatformForEmbedded/WPEWebKit#460]
Can WPE support multiple threads to handle WEB-GL?
It looks like WPE only use one thread to handle WEB-GL (ex: Java) from DS5 tool.

Or is there any recommended way to improve the webgl performance through configuration of WPE or Wayland?

**Comment by albertd** [comment]
No you can't have multiple webgl threads for now, but we have the non-compositing webgl flag that increases the performance by 2x.
