### ISSUE TITLE
Complex Domtree (incl css) & memory consumption?

### ISSUE THREAD

**Issue by woutervanh** [WebPlatformForEmbedded/WPEWebKit#461]
If I try to run following webpage on my imx6-platform with 1GB, whether on wayland backend or on viv_imx6-backend, it gives me a huge memory drop (till 0MB free) until it crashes. Sometimes it works, and then the memory gets back to normal. So it looks that only during build-up, memory drops. (checked via top during loading)
The page is normally generated by angular, which explains the huge domtree. (looks ugly, I know)
http://woutervh.html-5.me
What is happening here?

**Comment by albertd** [comment]
I think you're hitting some limitations of the device here, and if the GC kicks in in time it sometimes works, but even on my MacBook Pro it has trouble loading the page.

**Comment by woutervanh** [comment]
No, it was an issue of WPE trying to render zero-opacity layers.
Already fixed upstream:
https://bugs.webkit.org/show_bug.cgi?id=184143

**Comment by albertd** [comment]
@woutervanh ah cool, @zdobersek could you make sure this also gets into the wpe-2017 branch?

**Comment by clopez** [comment]
Its already merged in upstream stable 2.20 release
