### ISSUE TITLE
360 degree support at WPE Browser

### ISSUE THREAD

**Issue by karora123** [WebPlatformForEmbedded/WPEWebKit#463]
Does WPE Browser support video having 360 degree view. I have an attempt to view on Chrome which worked fine whereas at WPE Browser, video got overlapped.

**Comment by karora123** [comment]
Hi,

Any update on this?
I tried to run 
https://www.youtube.com/watch?v=NTcx0OHehdE
seems like 360 view not supported and video comes out like overlapped coordinates.

I have tried on tag release on 31st March, 2017.

**Comment by albertd** [comment]
@karora123 closing issue as we're not focussing on 360 support for now.
