### ISSUE TITLE
Canvas Goes Suddenly Black

### ISSUE THREAD

**Issue by ktxxt** [WebPlatformForEmbedded/WPEWebKit#474]
Hi,

I am experiencing a weird issue with my app. I am using Canvas and CSS3 on my RasperryPi 3. The app is launched in `wpe`.
After about 13 hours of running the app, all areas on screen (where HWA is used) go black. I'm using HTML5, CSS3 and Javascript/Canvas. 

I have done some detailed memory and performance testing and everything is fine. The code is optimized and there are no leaks.

This is my **/boot/wpe.conf**:
```
GST_GL_WINDOW=dummy

CAIRO_GL_COMPOSITOR=noaa
```

And this is my **/boot/config.txt**:

```
disable_splash=1
disable_overscan=1
boot_delay=0


arm_freq=1000
gpu_freq=500
over_voltage=6
avoid_warnings=1

gpu_mem_256=128
gpu_mem_512=196
gpu_mem_1024=256

kernel=zImage
initramfs initramfs.img

#device_tree=
#dtparam=i2c_arm=on
#dtparam=spi=on
#dtparam=i2s=on
dtoverlay=mmc
#dtoverlay=spi-bcm2708
#dtoverlay=rpi-ft5406

hdmi_force_hotplug=1
config_hdmi_boost=9
```

I have multiple devices which use the same app with same SD cards and configurations. The problem is occuring only on some RPis and its increasing.  After the problem occurs on a new device, it keeps happening every day. After rebooting everything is fine for multiple hours.

After researching several days, I couldn't find similar problems related this.

Could this be related to WPE or RPI?
Could it be due to RPi overheating, although the temp. never goes above 82C, but I'm not 100% sure.

If someone experiences similar issues, any help would be fine.

**Comment by ktxxt** [comment]
HI, @albertd,

I tried setting it to gpu_mem_1024=512, but the same thing happens. Also, on a newer installation if I dont set it at all or if I set it to 16, the problem does not happen. So I dont think the main problem is the gpu mem. All RPis are the same, there are no differences between them. 

@albertd, any other toughts?

**Comment by ktxxt** [comment]
Also, another question. What could be the cause for a RPI running out of memory? Assuming this would be the problem here instead of WPE itself.

**Comment by albertd** [comment]
Maybe build with the new WPE Framework, then you have all kinds of options to trigger garbage collection (memory pressure, etc) and if possible share the HTML example so we can try to reproduce.

**Comment by ktxxt** [comment]
I'll try it and let you know.

**Comment by albertd** [comment]
@ktxxt closing the issue for now, please re-open if still valid with latest greatest wpe-2017 branch.
