### ISSUE TITLE
Videos loading is consuming 3 seconds more time

### ISSUE THREAD

**Issue by ajay-parashar** [WebPlatformForEmbedded/WPEWebKit#476]
Hi,
I am using WPEWebkit on Raspberry Pi 0 .
I have tried git commit ce022f47929524ffb3acac3164702229cad94c38 released on 8th May 2018 and the link is  https://github.com/WebPlatformForEmbedded/WPEWebKit/commits/wpe-20170728.

I am facing the issue of 3 seconds late Videos loading on WPE. 

Please let me know
1) How can i use smooth video experience on RPI 0 ?
2) Is there any other known latest stable branch or tag that works smoothly with RPI 0 ?
I am using below option while building the WPEWebkit with buildroot , is this okay or i need to add more compile time switches.

BR2_PACKAGE_WPEWEBKIT=y
BR2_PACKAGE_WPELAUNCHER=y

BR2_PACKAGE_GSTREAMER1=y
BR2_PACKAGE_GSTREAMER1_GIT=y
BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_APP=y
BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_VIDEOCONVERT=y
BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_GIO=y
BR2_PACKAGE_GST1_PLUGINS_BASE_PLUGIN_OPUS=y
BR2_PACKAGE_GST1_PLUGINS_GOOD_PLUGIN_AUDIOFX=y
BR2_PACKAGE_GST1_PLUGINS_GOOD_PLUGIN_AUDIOPARSERS=y
BR2_PACKAGE_GST1_PLUGINS_GOOD_PLUGIN_AUTODETECT=y
BR2_PACKAGE_GST1_PLUGINS_GOOD_PLUGIN_DEINTERLACE=y
BR2_PACKAGE_GST1_PLUGINS_GOOD_PLUGIN_INTERLEAVE=y
BR2_PACKAGE_GST1_PLUGINS_GOOD_PLUGIN_MATROSKA=y
BR2_PACKAGE_GST1_PLUGINS_GOOD_PLUGIN_SOUPHTTPSRC=y
BR2_PACKAGE_GST1_PLUGINS_BAD_PLUGIN_MPEGTSDEMUX=y
BR2_PACKAGE_GST1_PLUGINS_BAD_PLUGIN_OPUS=y
BR2_PACKAGE_GST1_PLUGINS_BAD_PLUGIN_VIDEOPARSERS=y
BR2_PACKAGE_GST1_PLUGINS_BAD_PLUGIN_DASH=y
BR2_PACKAGE_GST1_PLUGINS_BAD_PLUGIN_FAAD=y
BR2_PACKAGE_GST1_PLUGINS_BAD_PLUGIN_HLS=y
BR2_PACKAGE_GST1_PLUGINS_BAD_PLUGIN_SMOOTHSTREAMING=y
BR2_PACKAGE_GST1_PLUGINS_UGLY=y
BR2_PACKAGE_GST1_PLUGINS_UGLY_PLUGIN_MPG123=y
BR2_PACKAGE_GST_OMX=y

**Comment by ajay-parashar** [comment]
hi,
If anyone knows the latest stable branch or tag that works smoothly with RPI 0 ?  please let me know .

**Comment by The-lost-cause** [comment]
No

**Comment by tohoangduy** [comment]
Which way that you use to play video? If can, you load the next video while playing the current video.

**Comment by calvaris** [comment]
Smooth video would be achieved with the OMX hardware decoders. They is no VP9 support though.
