### ISSUE TITLE
Issues compiling latest master branch for buildroot

### ISSUE THREAD

**Issue by T94T** [WebPlatformForEmbedded/WPEWebKit#483]
I'm writing here because there is no issues board for the WebPlatformForEmbedded/buildroot repository.

We are testing a lot with your buildroot implementation. Thanks for the great work you did so far!

There are some upcoming issues with the new master branch:

1. There is no WPELauncher anymore. Instead the WPEFramework is enabled by default. What is the idea behind that? Is there a way to have only the WPEWebKit running for production mode again?

2. There is no IMG generation anymore when using the _raspberrypi0_wpe_defconfig_ or _raspberrypi3_wpe_defconfig_. Why did you disable all the necessary settings?

3. Compiling the latest wpewebkit (200a16b241ff0c6a73e239c45345057d011f0193) throws following error:

`fatal error: CDMClearKey.h: No such file or directory`

**Comment by hlev** [comment]
I don't have the answers, but have you considered working with the `stable` branch instead? Tip of `master` isn't a safe bet for production.

**Comment by albertd** [comment]
@T94T We've moved to WPE Framework, which creates a smaller environment and also gives us integration into other subsystems for e.g. DRM.

1) WPE Framework is used already in production, so you're okay on that end. Furthermore it has a web interface to control, just goto http://<ip of device>

2) It's a zImage, so it boots from the fat32 partition and runs in memory, the ext4 is mounted to /root by default for caching of the browser

3) We can have a look, do you still have this with the latest master?

**Comment by T94T** [comment]
@albertd Thank you for taking your time to write me back.

1. Is still not clear to me.
3. I made a completely fresh install (took default raspberrypi0_wpe_defconfig), but still I get this same error:
`[3614/4503] fatal error: CDMClearKey.h: No such file or directory`

**Comment by albertd** [comment]
Latest commit in WPEWebKit solves the issue

**Comment by T94T** [comment]
Thanks. But could you please update the buildroot repository also? I still get the same error.
`fatal error: CDMClearKey.h: No such file or directory`
