### ISSUE TITLE
Build instructions for compiling for Ubuntu 16.4; Some addtional dependencies required

### ISSUE THREAD

**Issue by kjans** [WebPlatformForEmbedded/WPEWebKit#484]
In addition to your instructions:

$ sudo apt-get install intltool libtool-bin autoconf automake autopoint cmake gcc g++ bison flex gawk gperf ruby git libversion-perl libgnutls-dev libexpat-dev libxml2-dev libxslt-dev libsqlite3-dev libjpeg9-dev libfreetype6-dev libharfbuzz-dev libxcb-xkb-dev libwayland-dev libgbm-dev libgles2-mesa-dev libgstreamer1.0-dev libwebp-dev yasm ninja-build luajit libluajit-5.1-dev weston

It appears the that following are also required:
apt install libmount-dev
apt install libva-dev

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
