### ISSUE TITLE
encrypted dash content is not playing

### ISSUE THREAD

**Issue by goruklu** [WebPlatformForEmbedded/WPEWebKit#488]
with the most recent commits in wpe-20170728 branch, we are not able to play the encrypted DASH content. 
For example: http://www.gurdal-lab.net/dash.js/samples/playreadyMS.html

I tried the raspberry pi3 default buildroot image and that also failed

this old commit works: https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/9a2e61599c9a7bd24e59cd90fd2f2ff655c930ff

this one does not: https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/c699f32f92e227955b252528ed8ececa6118793e

In the old (working) version we see the following in the logs:
```0:00:01.886060851 27330   0x10d5b0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamerBase.cpp:383:handleSyncMessage: Handling drm-preferred-decryption-system-id need-context message for qtdemux0
0:00:01.886451814 27330   0x10d5b0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamerBase.cpp:401:handleSyncMessage: handling drm-preferred-decryption-system-id need context message
0:00:01.886820999 27330   0x10d5b0 INFO       webkitmediaplayer MediaPlayerPrivateGStreamerBase.cpp:451:handleSyncMessage: waiting for a CDM instance
0:00:01.886872814 27330 0xaee023c0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamerBase.cpp:445:operator(): scheduling initializationDataEncountered event with concatenated init data size of 802
http://www.gurdal-lab.net/dash.js/dist/dash.all.min.js:18:6279: CONSOLE LOG [1396] DRM: onNeedKey
http://www.gurdal-lab.net/dash.js/dist/dash.all.min.js:18:6279: CONSOLE LOG [1397] DRM: initData:
0:00:01.999979702 27330 0xaee023c0 ERROR      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:415:playbackPosition: Position 99:99:99.999999999
0:00:02.000162184 27330 0xaee023c0 ERROR      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:418:playbackPosition: buffered bytes 0
http://www.gurdal-lab.net/dash.js/dist/dash.all.min.js:18:6279: CONSOLE LOG [1510] DRM: KeySystem Access Granted (com.microsoft.playready)!  Selecting key system...

```

With the new revision, we see this:

```
0:00:02.865527588 15638 0xadc028a0 DEBUG              webkitmse MediaSourceClientGStreamerMSE.cpp:131:append: Appending 1622 bytes
0:00:02.865980810 15638   0x1155b0 WARN                 qtdemux qtdemux.c:6743:gst_qtdemux_process_adapter:<qtdemux0> Unknown fourcc while parsing header : free
0:00:02.866058106 15638   0x1155b0 WARN                 qtdemux qtdemux_types.c:224:qtdemux_type_get: unknown QuickTime node type pasp
0:00:02.866214255 15638   0x1155b0 WARN                 qtdemux qtdemux.c:9173:qtdemux_parse_segments:<qtdemux0> streaming; discarding edit list segments
0:00:02.866706180 15638   0x1155b0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamerBase.cpp:377:handleSyncMessage: Handling drm-preferred-decryption-system-id need-context message for qtdemux0
0:00:02.867133143 15638 0xadc028a0 DEBUG              webkitmse MediaPlayerPrivateGStreamerMSE.cpp:857:trackDetected: track ID: V1, caps: application/x-cenc, stream-format=(string)avc, alignment=(string)au, level=(string)2.2, profile=(string)constrained-baseline, codec_data=(buffer)0142c016ffe1001c6742c016a61105c6effc3214278c40000003004000000c07c58b846001000568c84232c8, width=(int)368, height=(int)208, pixel-aspect-ratio=(fraction)24960/19711, original-media-type=(string)video/x-h264, protection-system=(string)9a04f079-9840-4286-ab92-e65be0885f95
0:00:02.867241735 15638 0xadc028a0 ERROR             video-info video-info.c:415:gst_video_info_from_caps: wrong name 'application/x-cenc', expected video/ or image/
0:00:02.867269513 15638 0xadc028a0 DEBUG              webkitmse PlaybackPipeline.cpp:340:reattachTrack: Re-attaching track
```

**Comment by charlie-ht** [comment]
This is working correctly for me. I'm running `703a4a1d16` (latest as of 5 minutes OK). My environment,

```
output/build/wpeframework-9b495a733fd71675da8feb3adbda9af2f38edef1
output/build/wpeframework-cdmi-playready-089818c9f6db7cb0a8f7de9a4912a14fbd5f28dc
output/build/wpeframework-plugins-06798236f6b6cf8f105dc28803dd6de80f270961
output/build/wpeframework-provisioning-d7aa48c4e71b0888f1a5f0b59349433046c75da9
```

**Comment by goruklu** [comment]
@charlie-ht did you test it with RPi3 buildroot image ? 
I'll try to match your wpeframework component versions and test again.

**Comment by charlie-ht** [comment]
They should all be the defaults as of a recent buildroot revision, I don't have any overrides aside from webkit. This is with rpi3 defconfig.

**Comment by goruklu** [comment]
@charlie-ht My raspberry pie does not seem to be provisioned for playready or widevine. That's probably why I can't play encrypted content on it. What are the steps to get it provisioned ?

**Comment by albertd** [comment]
@goruklu we have our own internal provisioning servers for getting device certs towards the devices, you could build a standard PR and put the model cert and belonging files in the default location, on the top of my head /etc/playready

**Comment by goruklu** [comment]
@charlie-ht I'm still trying to understand why it's not working for us. 

Basically I'm seeing the MediaPlayerPrivateGstreamerBase::HandleSyncMessage() being called with drm-preferred-system-id need-context message but afterwards no protection events are generated.

webkitMediaCommonEncryptionDecryptTransformInPlace() times out waiting for a key.

In https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/02e24b4dca2147e6c0fa77f2d5a5b06e48b0ee5d @calvaris got rid of decryptor selection in demuxer (append pipeline) thread. I'm not sure I follow how it's supposed to work now.

**Comment by goruklu** [comment]
turns out one our patches was causing the issue. We can play encrypted dash content after removing that patch. thanks for your help.
