### ISSUE TITLE
SSL certs cannot be verified, CA certs missing?

### ISSUE THREAD

**Issue by towolf** [WebPlatformForEmbedded/WPEWebKit#489]
I built WPEWebkit using the buildroot method, and when I try to load HTTPS websites I get these messages:

![image](https://user-images.githubusercontent.com/345210/41232818-d95f6398-6d87-11e8-852e-1434466b7d0b.png)

Where is Webkit looking for the root certs?

In this file? `/etc/ssl/certs/ca-certificates.crt`

I also added the ca-certificates package using `BR2_PACKAGE_CA_CERTIFICATES=y` but that does not help either.

**Comment by albertd** [comment]
Yes that should be correct, if you're still facing this issue please reopen
