### ISSUE TITLE
wpe-westeros-image kernel panics on Rpi3

### ISSUE THREAD

**Issue by psivasubramanian** [WebPlatformForEmbedded/WPEWebKit#494]
I tried the wpe-westeros-image on Rpi3 using the instructions from https://github.com/WebPlatformForEmbedded/meta-wpe/wiki/Raspberry-PI last week & this week again (after repo sync), but seeing the same kernel panic on master & morty build with kernel v4.14. When I tried with kernel v4.9, not able to launch anything though it boots to shell prompt only. Need to check WPE (wpe-20170728 branch) with Westeros backend working on Rpi3. Any suggestions?

**Comment by albertd** [comment]
Closing issue here, please move this issue to meta-wpe if still relevant.
