### ISSUE TITLE
alloc() crash in ANGLE/PoolAlloc.cpp [wpe-20170728]

### ISSUE THREAD

**Issue by GlebNovodranPE** [WebPlatformForEmbedded/WPEWebKit#497]
Time to time WPEWebProcess crashes at Source/ThirdParty/ANGLE/src/compiler/translator/PoolAlloc.cpp : 324 with SIGSEGV.
https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/a0f5a8b284ad480b2c4b2769bc68ccd9feddc26e/Source/ThirdParty/ANGLE/src/compiler/translator/PoolAlloc.cpp#L324
Looks like the placement new construction happens upon an invalid pointer.
[core_bt.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/2149955/core_bt.txt)

The crash seems to happen upon a first shader code translation using ANGLE, within the 
first call to InitBuiltInSymbolTable, but at different places within the subsequent inner call to InsertBuiltInFunctions that use the pool allocation while filling in the symbol table.

Would you please bring the necessary commits that remove the ANGLE usage from master to wpe-20170728?

**Comment by magomez** [comment]
I'm currently cherry-picking some commits from the master branch to wpe-20170728, and they include some changes required for this issue. After I'm done with it, I'll check whether there are pending commits to fix this and cherry-pick them as well.

**Comment by magomez** [comment]
Please pull the latest changes on the wpe-20170728 branch, the problem should not be reproducible anymore there.

**Comment by GlebNovodranPE** [comment]
Thank you!
Gleb.
