### ISSUE TITLE
i.MX6: Is Hardware Acceleration for 2D Canvas supported?

### ISSUE THREAD

**Issue by telkamp** [WebPlatformForEmbedded/WPEWebKit#503]
We've got WPEWebkit running on our custom i.MX6D hardware, using Yocto Morty on Linux Kernel 4.9.11 (with meta-freescale layer) and vivante driver version imx-gpu-viv-5.0.11. 
We are using the framebuffer version of WPEWebKit (wpebackend-rdk) on a 800x480 pixel display.
We've noticed that HTML5 operations on a 2D canvas are not hardware accelerated (while WebGL operations are hardware accelerated). 
My question: Is hardware acceleration on a 2D canvas generally supported by WPEWebKit? Are there any tricks or hints how to enable it?

Note: A good benchmark is [http://fhtr.org/gravityring/sprites.html], running with 2-3 fps only on our WPEWebKit binary. 20fps should be normal. The WebEngine of Qt5 provides hardware acceleration for our 2D canvas on our i.MX6, but it seems to use a specific driver called "eglfs",

**Comment by rorbech** [comment]
There is a `2dcanvas` configuration option: `PACKAGECONFIG_append_pn-wpewebkit = " 2dcanvas"`. According to [this](https://github.com/Igalia/meta-webkit/wiki/PerformanceTips) you also need `PACKAGECONFIG_append_pn-cairo = " glesv2"`

**Comment by telkamp** [comment]
Thank you, we've tried both options - but it does not work on the i.MX6, at least with our kernel version. 2D canvas is still _not_ hardware accelerated. 
This might be an issue of the kernel and/or vivante drivers, so I'm curious to know if there is someone who got hardware acceleration running for 2D canvas on the i.MX6.
I think we should verify if we get have hardware acceleration when we use the Cairo library from an application without WPEWebkit.
