### ISSUE TITLE
WebProcess crash while loading animated content URL

### ISSUE THREAD

**Issue by nambirajang** [WebPlatformForEmbedded/WPEWebKit#515]
WebProcess is getting crashed with signal 11 while loading "https://edge.si-x1-production.top.comcast.net/" in STB.
This URL will show the STB's Wifi gateway details. If STB is not connected to Wifi gateway, Error message will be displayed  in animated Popup. During this popup rendering, crash  is observed.
![xfi_screen](https://user-images.githubusercontent.com/16299256/43229876-40e7e5f2-9034-11e8-9448-50e93602c133.jpg)

I have attached the working scenario url output screen.  
(Error message is shown in Pink color popup at top of screen)

We are seeing the crash in wpe desktop  build also.

Build details
branch: wpe-20170728
revision: c699f32f92e227955b252528ed8ececa6118793e
[coredump.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/2229683/coredump.txt)

**Comment by wouterlucas** [comment]
Doesn't crash for me, however I don't think it loads that pink color popup. Mind you I'm running this on a plain Broadcom Nexus 17.3 device without additional RDKV components.

![img_5101](https://user-images.githubusercontent.com/1534440/43279522-03edfe86-90c3-11e8-8b41-74a8a6db490e.png)

Tested with WPEWebKit 49781b6aa866f0ec7882360786eb5070beaa399e

Is there any way you can extract the offending graphical component which causes this so we can reproduce it without having a full-stack + setup + network?

**Comment by nambirajang** [comment]
Hi Wouter.
Can you please load the below url.
https://edge.si-x1-production.top.comcast.net/#access_token=CgNPQVQQARgCIoABFxj32tPFbTbFZMeWLjeOETx9iwSFpqpKP3HOuyH1wNuyQccMPC-GFI5SnsYcwbusURsUBZ5AKQhD7tmTGMBRYN06H0EU4QsousCzBRLzFGlWWMszOOkx4C77KRWLRKQpyKXzFQ535tBMmOroRxAwjnbZ9rQItTNVd1Pwk-X6EkUqEDYhnjcFpMlN6uikr03jw6YyUQoodXJuOmNpbWE6b2F1dGg6djI6YWNjZXNzLXRva2VuOmVuY3J5cHQ6MRIldXJuOmNpbWE6b2F1dGg6djI6YWNjZXNzLXRva2VuOnNpZ246MTqwAjX_tkPZ0lXlKmZGo8ak_kDvKJO_6l2NOwuiqQAjhIHz5bR2AK1Jxr5svlpLfp2e9Kyv6jR9OQS52N4N1Mxm4FhXVuOr-NbKFj87x__phkE4_IKPK0_pwhx1-5SKh6IZDnmfNWhzTtkOfd2tZDlLG3ijts6mU0W7Q2y7-8RqAXto_tcPcFDeJUQ2AbnDO2dUfG9CEGKPy7iho-7i1WIgpxQnW8m_lV3cQ5sro3xzIseg9QAr9HlwaFQp_IHoi_UoPvDRqtJxnqU4GV7pTiGKfh_MARp1PqetKi3xP1JbOQxT0hnavOUNSRgMnrQI5C3_fn5kDdP2GXv4SZjj1yuWzBwyHzjykdSb_v0R8BMgKo-eayGcjWRn9LKT4WQU2YoxGTMOusld920uUoKAulfrPVk*&token_type=Bearer&expires_in=3599&scope=openid%20profile%20email%20https%3A%2F%2Fsiorc.xfinity.com%2Fclient&id_token=eyJqa3UiOiJodHRwczpcL1wvb2F1dGgueGZpbml0eS5jb21cL29hdXRoXC9rZXlzXC9qd2tzIiwia2lkIjoiNEg2eGVtNDIzbU42cERJR29mNHFTZDR5R2Y0VWw5aVcwS0xMTHQtLUwtWSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJsb2dpbi5jb21jYXN0Lm5ldCIsInN1YiI6IjM2MjIyNTE0NjU5NDY0MTE5MTIwOTIwMTcuY3VzdCIsImF1ZCI6InNjaW9uIiwiYXpwIjoic2Npb24iLCJpYXQiOjE1MzI2MjgxOTksImV4cCI6MTUzMzMxMTA3OCwiYXV0aF90aW1lIjoxNTMyMDk3ODc4LCJwcmV2X2F1dGhfdGltZSI6MTUzMjYxOTYxOCwiYW1yIjpbInVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlBhc3N3b3JkUHJvdGVjdGVkVHJhbnNwb3J0Il0sImFjciI6InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlBhc3N3b3JkUHJvdGVjdGVkVHJhbnNwb3J0IiwidXNlcl90eXBlIjoiUmVzaWRlbnRpYWwiLCJybV9zdGF0ZSI6ZmFsc2UsImxvZ2luX2lkIjoiUkFKQU5OQU1CSUBjb21jYXN0Lm5ldCIsInRpZCI6IjQzNTRjZjUwMWMxZGY2YjM4ZjA3LTg3NTg0NTIwYjhiNWRkMDQ2NjE1ZmM4MWY3Y2VhMjEwYmJiNGFmNGUifQ.N3oAX9sNECEZn1PhjcoeOulUkqjL7yWF57YnFFCXuftRE7Vy90Y-ZaYVtG83Mveu1rj1SvWHrYv_j1YxZwn5bcrPZFPwvYgudZ9SRSaaljTZP_wtsdMfoJ4ZKsYzF8J5KklYQSA0p2RWDwo8q2JJlhhVRvtQXLaY_29PA75hXWA


If you load this url in chrome, you would see the ping color popup (toaster) in top.
In wpe-20170728 branch, you will see the crash.

**Comment by wouterlucas** [comment]
Yep that does it! Thank you @nambirajang

**Comment by igor-borovkov** [comment]
we tried to extract linear-gradient and webkit-transform applied to that div, with z-order included, etc etc, but it doesn't lead to a crash, there are probably multiple things playing into the crash.  @nambirajang  can you post an html code that we used to try to reproduce this crash unsuccessfully ?

**Comment by nambirajang** [comment]
@igor-borovkov @wouterlucas , Here I have attached the test.html which we tried to simulate the scenario. But it didn't crash.

[test-html.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/2233461/test-html.txt)

**Comment by nambirajang** [comment]
Hi @wouterlucas @igor-borovkov ,
Can you please cherry-pick this change 9d23ca0cc445b9f3ea3aaa6dc0b06c21c26a8844 to wpe-20170728 branch to avoid this crash.

**Comment by wouterlucas** [comment]
Thanks! I raised https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/517 for cross-check. Will get this in asap.
