### ISSUE TITLE
WPELauncher doesn't show line number for JavaScript errors

### ISSUE THREAD

**Issue by ganeshprasads** [WebPlatformForEmbedded/WPEWebKit#520]
WPE Launcher is not able to show the line number with error messages when running Java Script code.
Example Snippet:
`        <script>
            function b(){
                var x = b.y.z;
                console.log( x );
            }
            b();
        </script>
`
Console error message:
`CONSOLE ERROR TypeError: undefined is not an object`
Expected error message (tested with Mozilla):
`TypeError: b.y is undefined[Learn More]  test.html:6:9`

**Comment by wouterlucas** [comment]
I think you are comparing Chrome debugger output to WebKit debugger output.

If I run the same on Safari (WebKit) I get:
> function b(){ var x = b.y.z; console.log( x ); } b(); 
< TypeError: undefined is not an object (evaluating 'b.y.z')

**Comment by albertd** [comment]
Use the webinspector that makes it easier to debug.
