### ISSUE TITLE
2D Hardware Acceleration: WPEWebkit vs. Chromium

### ISSUE THREAD

**Issue by telkamp** [WebPlatformForEmbedded/WPEWebKit#528]
We are running WPEWebkit on a custom i.MX6D hardware using Yocto Rocko, Linux Kernel 4.9.11 and GPU driver imx-gpu-viv_6.2.2.p0 (Vivante).
Using the GPU benchmark http://www.smashcat.org/av/canvas_test we observe a much lesser performance compared to the Qt WebEngine (based on Google Chromium):
* WPE Webkit with ENABLE_ACCELERATED_2D_CANVAS=ON: ca. 15fps
* WPE Webkit with ENABLE_ACCELERATED_2D_CANVAS=OFF: ca. 10fps
* Qt WebEngine (based on Chromium 54.0.2810.2): ca. 45fps

This was really surprising for me, so I would like to know if other users think that this is an expected behaviour, or if we might have to look for a problem with our WPEWebkit, Linux kernel or vivante driver.

Thank you!

**Comment by albertd** [comment]
Can you try using the following export:

CAIRO_GL_COMPOSITOR=noaa

**Comment by telkamp** [comment]
Thank you for the hint! The patch seems to be missing in the master - fortunately it was available in a ticket.
But anyway, it does not help - no difference in fps if CAIRO_GL_COMPOSITOR=noaa is set or not.
Any more ideas?

**Comment by albertd** [comment]
![smashcat-rpi3](https://user-images.githubusercontent.com/2719571/45093447-b2afd780-b118-11e8-8538-3da3dabfdc06.png)
I'm getting 87~89 fps on the RPI3, hardware is comparable?

**Comment by telkamp** [comment]
The RPi3 Hardware seems to be more powerful than the i.MX6DL:
RPi3: ARM CortexA53 (64 Bit), 4 Cores, 1200MHz, GPU Broadcom Dual Core VideoCore IV
i.MX6: ARM Cortex A9, 2 Cores, 1000MHz, GPU Vivante GC320

Our display solution is 800x480. Have you run the test on FB or Wayland?
But anyway, the difference in hardware does not explain the difference in fps, I think... There must be a trick in the configuration; in particular because we get 45fps using chromium 54.x in wayland...

**Comment by albertd** [comment]
@telkamp closing this issue, we're working on refactoring the whole graphics to move away from Cairo. this will help in the canvas 2d performance as well, currently I would recommend using webgl as that is the fastest render path. Please have a look at our [Lightning](https://github.com/WebPlatformForEmbedded/Lightning) framework which will help during the development. You can increase the performance of the webgl using the non-compositing-webgl flag which is part of the configuration.

**Comment by telkamp** [comment]
@albertd: Thanks for the info! 
Can you say what will be used instead of Cairo in future?
We'll have a look on Lightning.

**Comment by albertd** [comment]
The team has been working on something that is internal into webkit.
