### ISSUE TITLE
Remote webInspector with WPE gives error

### ISSUE THREAD

**Issue by deeps8us** [WebPlatformForEmbedded/WPEWebKit#534]
I'm trying to access remote web inspector on wpe yocto stack
export WEBKIT_INSPECTOR_SERVER=:::9222

netstat -anp | grep 9222
shows
tcp        0      0 :::9222                 :::*                    LISTEN      13117

But when I access Web Inspector from my PC, got the error message :
Error: 0, The resource at '/org/wpe/inspector/UserInterface/inspectorPageIndex.html' does not exist occurred during fetching inspector resource files.

**Comment by aperezdc** [comment]
Do you have `libWPEInspectorResources.so` installed in your system? (Typically it would be under `/usr/lib`)

**Comment by deeps8us** [comment]
We dont have that library. Is that why the error is happening? Can you please provide more details about that. How to enable/build.

**Comment by aperezdc** [comment]
@deeps8us The normal WPE build process also compiles `libWPEInspectorResource.so`, so I suppose that what is happening is that it is *not* being installed by the Yocto recipes. Are you using the `meta-browser` layer? If yes, this library needed by the remote inspector is part of the `wpewebkit-web-inspector-plugin` package. Make sure you add it in the list of packages installed to the target images.

**Comment by deeps8us** [comment]
Thank you for the information.
