### ISSUE TITLE
JSC Crash in methodTable

### ISSUE THREAD

**Issue by Gavriliuk** [WebPlatformForEmbedded/WPEWebKit#543]
WPEWebProcess crashes with signal SIGSEGV

The stacktrace of the crashed thread contains only 2 lines:

Frame | Signature | Module | Source
-- | -- | -- | --
#0 | methodTable | libWPEWebKit.so.0.0.20161117 | JavaScriptCore/runtime/JSCellInlines.h:217
#1 | create | libWPEWebKit.so.0.0.20161117 | JavaScriptCore/API/APICast.h:81

**Comment by wouterlucas** [comment]
Hi @Gavriliuk:
What kind of device? MIPS, ARM?
How can we reproduce?
How often does this happen?

**Comment by Gavriliuk** [comment]
Hi @wouterlucas 

This crash was reproduced 4 times for the recent 30 days on the same STB
Samsung Electronics Co SX022AN Digital Set Top Box
OS Linux 3.3.8-2.2 #1 SMP mips CPU 2 cores

Steps to reproduce are unknown

**Comment by albertd** [comment]
@Gavriliuk please reopen if the ticket is still valid, if so please add a bit more info, which commit hash of wpewebkit and which application etc.
