### ISSUE TITLE
WPE emits "WAITING" signals on video element when it should not

### ISSUE THREAD

**Issue by frperzent** [WebPlatformForEmbedded/WPEWebKit#550]
Using a simple piece of HTML code with a video tag playing a mp4 file, with an attached event listener, I can see that during the course of video playback, the video tag element receives a steady flow (about every 10-15 seconds usually) of WAITING events. (https://developer.mozilla.org/en-US/docs/Web/Events/waiting)

I have tried several other browsers under the same network conditions, and I do not see this event from any of them.

Is this a known problem? How can this behaviour be explained? Can it be fixed?

**Comment by albertd** [comment]
@frperzent please retest, but should be okay now on the wpe-2017 branch
