### ISSUE TITLE
Incorrect display of texts that are truncated with ellipsis

### ISSUE THREAD

**Issue by mladenlazic** [WebPlatformForEmbedded/WPEWebKit#551]
Text that is cut with CSS and Ellipse is not rendered correctly on the screen. The behavior changes when you change the letter spacing of the font. The same example is tested on epiphany browser, it works. HTML example and picture are added below.

WPE vs Epiphany:
![epiphany_vs_wpe](https://user-images.githubusercontent.com/11682725/47909373-09732c80-de90-11e8-8cd1-d6a24ba70153.png)
On the picture, the first window is WPE browser (just one dot is visible), the second window is Epiphany browser (three dots are visible).

Test example:
[test.tar.gz](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/2541995/test.tar.gz)

Can it be fixed?

**Comment by aperezdc** [comment]
The reason for this difference might be that the GTK+ port always uses the complex text layout code path, while WPE in some cases uses the simple layout one.

**Comment by albertd** [comment]
@aperezdc, @magomez something we can still cherry-pick for the wpe-2017 branch?

**Comment by mladenlazic** [comment]
This issue is fixed on WPE 2.22. Thank you all.
