### ISSUE TITLE
WebKitBrowser issues with external URLs

### ISSUE THREAD

**Issue by T94T** [WebPlatformForEmbedded/WPEWebKit#554]
When changing the URL in WebKitBrowser.json to an external address (eg. https://www.google.com), the browser keeps white after boot. When clicking `RELOAD` in the `Presets / URL` section of the Controller interface, the page gets loaded. 
Localhost URL and an external IP address just work - WebKitBrowser starts and shows the correct content.

After a while (between 30s and 2m) after booting, Controller interface is not reachable anymore. System works just fine though.

**Comment by albertd** [comment]
As the setup is now the browser is loaded before the network is up, please change the location of the url after this line in the [index.html](https://github.com/WebPlatformForEmbedded/buildroot/blob/master/board/raspberrypi/index.html#L259)

Adding a `location.href = "https://www.google.com";` should do the trick.
