### ISSUE TITLE
Creating new JS window object from c++ code

### ISSUE THREAD

**Issue by madanagopalt** [WebPlatformForEmbedded/WPEWebKit#6]
Hi,
I am using WPE Webkit. I want to create new JS window object (i.e new window.XX) and map it to the c++ function. Could you please tell the way to do this. Thanks.

Regards,
Madan

**Comment by blino** [comment]
You can check the injected bundle example from this repository:
https://github.com/Metrological/wpe-launcher

It shows how to inject JS objects and functions.
