### ISSUE TITLE
buildroot: update nodejs

### ISSUE THREAD

**Issue by Lange** [WebPlatformForEmbedded/WPEWebKit#608]
Hello, apologies if this issue is in the wrong place or covered elsewhere.

I'm looking to use WPE on my Raspberry Pi 3 via [WebPlatformForEmbedded/buildroot](https://github.com/WebPlatformForEmbedded/buildroot). However, this buildroot fork produces images with a pretty old, unstable, and unsupported version of nodejs (v7.7.2). Are there any plans to upgrade to a currently-supported LTS release, such as v10?

Thanks for your time,
Alex

**Comment by T94T** [comment]
You can take precompiled binaries from https://nodejs.org/download/release and put them into the `rootfs_overlay/usr/bin/` folder.

**Comment by Lange** [comment]
Oh nice! I had no idea.
